### ISSUE TITLE
Auto complete for JS code in HTML file

### ISSUE THREAD

**Issue by stoskov** [marijnh/tern#230]
Auto complete in HTML file for js code in script tags seems to ignore the first function declaration.

In the following code the Tern only gives test2 and test3 as available options:

	function test1 () {}             
	function test2 () {}        
	function test3 () {}        
          
If the script tag starts with variable declaration auto complete shows all the functions and the variable. 

In the following code the Tern shows all the identifiers as available options (test1, test2, test3, and test4).

	var test4;
	function test1 () {}             
	function test2 () {}   
	function test3 () {}   

http://screencast.com/t/ZlUmAVbLlGiW

Is this a bug?

Thank you!

**Comment by angelozerr** [comment]
If you wish to use tern inside HTML file, please try https://github.com/angelozerr/tern-browser-extension

**Comment by stoskov** [comment]
We have workaround it, but thanks for the suggestion.

**Comment by angelozerr** [comment]
@stoskov https://github.com/angelozerr/tern-browser-extension provides not only extraction of JS from HTML. It provides too completion and go at definition for HTML elements ids : 

```html
<div id="MyId" ></div>
<script>
  document.getElementById(' // here Ctrl+Space shows MyId
</script>
```
