### ISSUE TITLE
Can't eagerly load all js files with "**/*.js"

### ISSUE THREAD

**Issue by jeroentbt** [marijnh/tern#281]
When using tern on a meteor project (using [Slava's meteor plugin](https://github.com/Slava/tern-meteor)), I would like all my .js files to be loaded in to tern.

In .tern-project,
`"loadEagerly": ["**/*.js"]`
does not seem to work
`"loadEagerly": ["*.js","*/*.js","*/*/*.js","*/*/*/*.js"]`
does.

**Comment by Slava** [comment]
This issue is a year old and is somewhat related to my project at Slava/tern-meteor. Since I recently worked on a fork of tern for Meteor for Sublime Text, I debugged this issue and didn't find anything abnormal as of March 2015. I propose on closing this ticket.
