### ISSUE TITLE
Tern & Javascript defined in HTML page

### ISSUE THREAD

**Issue by angelozerr** [marijnh/tern#360]
@marijnh I'm supporting completion, lint, etc with tern inside an HTML editor (Eclipse IDE) where Javascript is defined inside script elements : 

---------------------------------------
	<html>
	  <script>var a = [];</script>
	  <script>a.</script>
	</html>
---------------------------------------

The first solution I have found is to post the full HTML file in tern server. It works but tern lint set errors for HTML content.

The second idea is to replace with space HTML content : 

---------------------------------------
	     
	              var a = [];
                      a.</script>

---------------------------------------

The replacement is done in client side (Java). But I tell me that this replacement could be doen on server side by tern? Files could be flagged as HTML to avoid doing this replacement even with simple JS files.

**Comment by mrennie** [comment]
For what its worth, that is how we use Tern + ESLint, etc in Orion: we regex out the script blocks into a 'file' and run that through the tools:

See https://github.com/eclipse/orion.client/blob/master/bundles/org.eclipse.orion.client.javascript/web/javascript/finder.js#L690

**Comment by angelozerr** [comment]
@mrennie please try https://github.com/angelozerr/tern-browser-extension, the basic idea is to extract JavaScript content from HTML file with new preParse callback. The extraction is done with SAX (sax-js). This tern plugin provides too extra features like completion, hyperlink for element ids : 

![CodeMirror & GetElementById completion](https://github.com/angelozerr/tern-browser-extension/wiki/images/CodeMirror_GetElementByIdCompletions.png)

 * go at the definition of the attribute id : 
 
![CodeMirror & GetElementById definition](https://github.com/angelozerr/tern-browser-extension/wiki/images/CodeMirror_GetElementByIdDefinition.png)

Don't hesitate to create PR or issues if you like it.

I close this issue since tern provides preParse callback (not released)
