### ISSUE TITLE
make infer.js work when `eval` is forbidden 

### ISSUE THREAD

**Issue by gfwilliams** [marijnh/tern#385]
Sadly this is a problem because Google Chrome Web Apps don't allow `eval` or `Function`.

There's a thread on this for acorn, and a script [has just been contributed](https://github.com/marijnh/acorn/issues/90#issuecomment-54801135) which fixes it for that.

Once that is applied, you're left with another failure which is from this code in infer.js which uses `Function.apply`:

```
  var constraint = exports.constraint = function(props, methods) {
    var body = "this.init();";
    props = props ? props.split(", ") : [];
    for (var i = 0; i < props.length; ++i)
      body += "this." + props[i] + " = " + props[i] + ";";
    var ctor = Function.apply(null, props.concat([body]));
    ctor.prototype = Object.create(Constraint.prototype);
    for (var m in methods) if (methods.hasOwnProperty(m)) ctor.prototype[m] = methods[m];
    return ctor;
  };
```

I've come up with this, which seems to work - however looking more closely at what's being done above I think it's probably wrong, so I'd really appreciate any input.

If it's ok I'd be happy to issue a pull request (however I assume that the original implementation was created for a good reason :) ).

```
  var constraint = exports.constraint = function(props, methods) {
    props = props ? props.split(", ") : [];
    var ctor = function() {
      this.init();
      for (var i = 0; i < props.length; ++i)
        this[props[i]] = arguments[i];
    };
    ctor.prototype = Object.create(Constraint.prototype);
    for (var m in methods) if (methods.hasOwnProperty(m)) ctor.prototype[m] = methods[m];
    return ctor;
  };
```

**Comment by mamacdon** [comment]
Hey, so I'm having to patch this to make Tern work in our Chrome app. I could submit a PR while I'm at it.

Is a simple `try..catch` fallback good enough, or are you expecting a shell script that generates a CSP-safe variant of `infer.js`, like Acorn does?

**Comment by marijnh** [comment]
Attached patch removes the use of `new Function` entirely. I'm still pissed that Chrome is breaking this feature of the language, but so it goes.

**Comment by mamacdon** [comment]
Thanks for the fix.

**Comment by gfwilliams** [comment]
Thanks! It is frustrating about Chrome - I'm not convinced it makes anything more secure either (which I assume was their rationale), as you could just write a JS interpreter in JS and still execute arbitrary code.
