### ISSUE TITLE
Support multiple types in JSDoc typing

### ISSUE THREAD

**Issue by p-bakker** [marijnh/tern#427]
In JSDoc you can type for example a parameter to allow multiple types, like this:
@param {String|Number} myParamName description

Same thing goes for @type

Tern doesn't seem to recognize this.

**Comment by RReverser** [comment]
Any updates on this?

**Comment by p-bakker** [comment]
I started on it, got stuck and then got completely sidetracked, so unfortunately no progress.

And no idea when I might get around to it now

**Comment by marijnh** [comment]
Please take a look at patches 4604a1e747a89...29bcf0adc53 and see whether they reflect what you had in mind.

**Comment by RReverser** [comment]
Yes, thanks!

**Comment by RReverser** [comment]
@marijnh There is problem though:

```javascript
function a(x) {} a(1)
function b(x) {} b("x")

var t = Math.random() > 0.5 ? a : b;
t( // shows only `t(x: number)` here while should be `t(x: number|string)` or at least `t(x: number)|t(x: string)`
```

**Comment by marijnh** [comment]
To do what you are expecting here, we'd need a unification algorithm that goes from two function types to a single function type with union arguments. That's not how completion and type resolution currently works. Though if you want to look into it, the way to do it would be to replace `similarType` in `infer.js` with a `unifyTypes` function that, given two types, either returns a unified type or null if they are incompatible.

**Comment by sevin7676** [comment]
I would like to see this functionality as well. I implemented a quick hack into my tern plugin that allows fake union types by simply reproducing what ever type is listed in the jsdoc param *(its far from perfect, but works until I can get official Tern support)*. 

Try the following code in [my demo] (http://sevin7676.github.io/Ace.Tern/demo.html):


```javascript

/**
 * @param {string|number} a - first part of addition
 * @param {string|number} [b] -second part of addition  
 */
function add(a,b){
    if (b == null) return a
    return a+b;
}

add(1,2);

```

**Comment by marijnh** [comment]
@sevin7676 Did you think to try the current Tern version? Your example code already works there.

**Comment by sevin7676** [comment]
that's awesome! I actually wrote my code about 6 months ago, and at that time there was no such support. Thanks!

**Comment by marijnh** [comment]
@RReverser On closer look, I don't think your example really is something that is important to support. The value in `t` would _not_ be a function that takes a number or a string, it would in fact be either a function that takes a number, or a function that takes a string. In terms of typing, that is not a very useful situation. So I've decided not to move to a unification algorithm, and I'm closing this issue.
