### ISSUE TITLE
What about ecma6.json?

### ISSUE THREAD

**Issue by angelozerr** [marijnh/tern#465]
@marijnh I tell me if you plan to write the ecma6.json JSON Type Definition to benefit for instance with TypedArray, Float32Array, etc https://developer.mozilla.org/en-US/docs/Web/JavaScript/Typed_arrays

**Comment by marijnh** [comment]
I would be very happy if someone would undertake this. It is probably best done as an addition, a file that expects `ecma5.json` to be loaded first, and adds the additional bindings created by ES6. Personally, I have too much to do right now to work on this.

**Comment by angelozerr** [comment]
Ok @marijnh I would like just know that because https://github.com/daniel-lundin/tern-snabbt needed Float32Array I have added inside the plugin for the moment.

**Comment by angelozerr** [comment]
@marijnh you have written ecma5.json at hand? I tell me if we could generate it from https://developer.mozilla.org/en-US/docs/Web/JavaScript/Typed_arrays ?

**Comment by marijnh** [comment]
Yes, I wrote it mostly by hand using MDN and the standad as references, doing some ad-hoc automation for generating MDN urls and pulling docstrings from there.

**Comment by angelozerr** [comment]
> Yes, I wrote it mostly by hand using MDN and the standad as references, doing some ad-hoc automation for generating MDN urls and pulling docstrings from there.

Wow, it's a big work!

> It is probably best done as an addition, a file that expects ecma5.json to be loaded first,

As tern doesn't support version, I think it should be better that ecma6.json depends NOT on ecma5.json. For instance ES6 provides new functions for Array like Array#entries
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/entries

**Comment by angelozerr** [comment]
Ok @marijnh forhet my comments, tern is enable to merge several definitions (I have tested by creating a new function for Array in ecma6.json and it works great (both functions of Array of ecma5 + ecma6 appears in the completion).

I will try to generate ecma6.json from https://developer.mozilla.org/en-US/docs/Web/JavaScript/New_in_JavaScript/ECMAScript_6_support_in_Mozilla

It will not perfect but after we could change it at hand to redefine !type with better mean. Are you OK with that?

**Comment by angelozerr** [comment]
@marijnh for your info, I have started ecma6.json that I have generated from  https://developer.mozilla.org//en-US/docs/Web/JavaScript/New_in_JavaScript/ECMAScript_6_support_in_Mozilla

I must update the generated ecma6 to fill "!type" You can see my current work at https://github.com/angelozerr/tern/blob/patch-13/defs/ecma6.json 

I will do a PR once I will finish my work, but it will not perfect. For instance I don't know how to manage iterator https://developer.mozilla.org/en-US/docs/Web/JavaScript/Guide/The_Iterator_protocol used in https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Map/entries

**Comment by angelozerr** [comment]
@marijnh please see PR https://github.com/marijnh/tern/pull/475

**Comment by angelozerr** [comment]
Tern provides now https://github.com/marijnh/tern/blob/master/defs/ecma6.json. 

Note that if you wish to use ecma6.json, you must declare too ecma5.json in your .tern-project : 

```json
{"libs":["ecma5","ecma6"]}
```

Thanks @marijnh to have accepted the ecma6.json PR.
