### ISSUE TITLE
!span property in json definition

### ISSUE THREAD

**Issue by madhavan020985** [marijnh/tern#466]
````javascript
{
  "!define": {
    "b.<i>": {
      "!span": "14[1:2]-15[1:3]",
      "!type": "[b.<i>]",
    }
  }
````
what does the !span property mean here? Can someone kindly update it here, http://ternjs.net/doc/manual.html
(or) for that matter, all tern schema keywords (!define, !name, !type, !doc, !url........)can be added in the manual. It will serve a lot of purpose, i mean...

**Comment by marijnh** [comment]
It indicates the position in the file where this property was (first) defined. You wouldn't use this for hand-written definition files. `!doc`, `!url`, and `!define` _are_ all described in the manual.
