### ISSUE TITLE
bin/condense with "doc" property

### ISSUE THREAD

**Issue by tmcw** [marijnh/tern#470]
Possibly `bin/condense` is not the best place to look for this: how would one use tern to get full data for all methods? So, `bin/condense` except it wouldn't simplify the internal data structure at all, and would be potentially useful for generating documentation?

**Comment by marijnh** [comment]
You mean you want to include local variables? I guess you'd have to invent a file format (an extension of the json files which can also express locals), and extend `bin/condense` to output it. This is not something I'm going to work on, so I'm closing this issue (which is more of a support request anyway.)
