### ISSUE TITLE
functional condense() method

### ISSUE THREAD

**Issue by tmcw** [marijnh/tern#472]
Right now `condense()` relies on a server's state indirectly as a global. Could there instead be a method for a tern server to dump its current state and context would take that as an argument, so that it would be possible to implement something like `condense()` (like #470) without being within the tern package?

**Comment by marijnh** [comment]
I think you are confusing the 'dynamic' variable `infer.cx()` with a global. You can run condense in the context of any server using `infer.withContext`. It would even be possible to create a plugin that defines a new query type to dump the server's current definitions for a given set of origins.
