### ISSUE TITLE
How to manage !effect or !custom with simple property.

### ISSUE THREAD

**Issue by angelozerr** [marijnh/tern#473]
I'm writing a tern plugin for jasmine https://github.com/angelozerr/tern-jasmine 

I can manage this case : 

```javascript
expect(true).  // here Ctrl+Space must shows not, toBeDefined, etc
```

expect is a function which returns a custom function (because jasmine matchers can be dynamic). 

```json
"expect": {
      "!type": "fn(value: ?) -> !custom:jasmineExpect",
      "!doc": "Expectations are built with the function expect which takes a value, called the actual. It is chained with a Matcher function, which takes the expected value."
    },
```

See https://github.com/angelozerr/tern-jasmine/blob/master/jasmine.js#L146

The `not` matcher must return the matchers list too like expect function (`not', 'toBeDefined', etc, So I have written :

```json
"not": {
          "!type": "!custom:jasmineExpect",
```

But as `not` matcher is a property and not a function, it doesn't work. 

I would like to manage that : 

```javascript
expect(true).not.  // here Ctrl+Space must shows not, toBeDefined, etc
```
@marijnh have you an idea how to I could manage not case?

**Comment by marijnh** [comment]
What does `not` hold, then? Is it a getter property? If it's not a function, Tern can currently not associate effects with it.

**Comment by angelozerr** [comment]
not is a simple property. That's why I have created an issue for that : associate an effects with a property. 

I have fixed my problem by writing my JSON Type Defitnition with an other mean and it works https://github.com/angelozerr/tern-jasmine/blob/master/jasmine.js#L47
