### ISSUE TITLE
Tern does not infer types through promises.

### ISSUE THREAD

**Issue by mseddon** [marijnh/tern#486]
Using either Promise or Q, tern fails to infer the type of the success handler arguments.  I wouldn't say this is a limitation of the tern type inferencer, but it seems like a good candidate for a plugin.  Before I look too far into implementing one I was wondering:

  a) does such a plugin exist?
  b) is this possible with a plugin?
  c) how much pain would be involved implementing such a plugin?

And perhaps, more abstractly:
  d) is there a central location where developers contribute their tern plugins?

**Comment by angelozerr** [comment]
> a) does such a plugin exist?

Promise is for ECMAScript6. Today tern provides only ecma5.json 

I have created a PR for ecma6.json https://github.com/marijnh/tern/pull/475

But it's very basic. I think Promise should be improved https://github.com/marijnh/tern/pull/475/files#diff-86d0e1883fb47a3188ad9f50734bc5deR465

> b) is this possible with a plugin?

here it's a JSON Type Definition. I think Promise should be improved with custom inference function (infer.registerFunction).

> d) is there a central location where developers contribute their tern plugins?

No but I have created this issues https://github.com/marijnh/tern/issues/424 We would like to provide a plugins.json which list the whole tern plugins.

I try to integrate tern plugins see https://github.com/angelozerr/tern.java/wiki/Getting-Started#tern-modules

To search tern plugins today, you can use those 2 urls : 

 * https://www.npmjs.com/search?q=tern
 * https://github.com/search?o=desc&q=tern&s=updated&type=Repositories

**Comment by marijnh** [comment]
Patch 57cf35fadd802a8 adds some magic to the definition of Promises in ecma6.json to make Tern mostly able to see through them, as far as result values are concerned. Let me know whether that works for you (you'll have to include the ecma6 defs to get it).

**Comment by mseddon** [comment]
Yes, this is exactly the sort of thing I'm looking for :+1:

If I get some time, I will attempt a Q plugin based around this.

**Comment by othree** [comment]
I like to add [fetch](https://fetch.spec.whatwg.org/) def file
But I don't know how to assign the result of Promise in def.
Here is what I expect:

    "fetch": {
      "!type": "fn(url: string) -> +Promise[value=string]"
     }

I copy the return type format from `Promise.resolve`.
But the function parameter  in `then` is still `?`
Is it possible to given a specified fulfill value for promise in def file now?

**Comment by marijnh** [comment]
@othree That was a type parser issue. Patch 0958506 solves it.

**Comment by othree** [comment]
Thanks @marijnh 

It looks work great but still have some problem.
I complete the [fetch.json](https://github.com/othree/tern/blob/6b76fd438861ec2f08a55c96c596e83d09d2bf06/defs/fetch.json) file.
And use it with following codes:

    fetch().then(function(res) {
      res;
      res.blob().then(function (bbb) {
        bbb
      });
    });

The first strange behavior I found is that `bbb` is not a blob object.
So I use `TernType` to inspect.
And it shows `res` is `ArrayBuffer|string`, not `Response`.
But `res` did have method and properties of `Response`.
`bbb` is similar as `res`.

**Comment by othree** [comment]
Finally I got this solved.
I forgot to include `ecma6` in my project.
