### ISSUE TITLE
query.guess returns bizarre completion

### ISSUE THREAD

**Issue by angelozerr** [marijnh/tern#488]
I would liek to know if it's the known behaviour with following sample : 

![ternguess](https://cloud.githubusercontent.com/assets/1932211/5898327/b634e730-a54e-11e4-8b50-23cc1a72bedd.png)

```javascript
var a = {};
a.add // here Ctrl+Space shows addBlack, etc
```

After debugging the demo, this case comes from  this code : 

```javascript
if (!completions.length && word.length >= 2 && query.guess !== false)
        for (var prop in srv.cx.props) gather(prop, srv.cx.props[prop][0], 0);
```

See https://github.com/marijnh/tern/blob/master/lib/tern.js#L696

I don't understand which use cases this code line manage?

I could set query guess to false, but I'm afraid that I loose the case with objType.guessProperties.

@marijnh Thanks for your clarification.

**Comment by marijnh** [comment]
If the completion code can't find any completions from the type of the object, it will simply try to match the typed text against all properties that were seen in the program, in the assumption that you're likely to be looking for a property name that was used before. That's what you are seeing here.
