### ISSUE TITLE
RangeError: Maximum call stack size exceeded

### ISSUE THREAD

**Issue by angelozerr** [marijnh/tern#492]
When I try to use tern completion with node.js with a lot of JS files (for instance with this project https://github.com/joyent/node). I have the following errors

```
RangeError: Maximum call stack size exceeded
```

When I comment `infer.toString(val)` (inside `gather` see https://github.com/marijnh/tern/blob/master/lib/tern.js#L630) I have not this error.

Perhaps this problem comes from with union type?

**Comment by piotrtomiak** [comment]
This issue seems to be a regression with regards to at least 0.7.0. We are experiencing it on a large codebase, for which Tern 0.7.0 worked a bit slow, but was usable. The latest version just throws this error and terminates.

**Comment by angelozerr** [comment]
@piotrtomiak yes it's my fault I have integrated last sources fo ternjs although @marijnh is developping the union type feature.

I'm waiting for @marijnh answer to try to fix it, but he's very busy.

**Comment by piotrtomiak** [comment]
@angelozerr, thanks for info, I think I'll just revert your commit (to go back to Tern 0.8.0) until this is fixed.

**Comment by marijnh** [comment]
@angelozerr Can you tell me which type is being given to `toString` when the recursion occurs? And given that information, can you maybe produce a reduced test case? I have no idea what to do to reproduce it with the node codebase.

**Comment by angelozerr** [comment]
@marijnh I have reverted ternjs for the moment. I will retry when I will find time to give you more info.

**Comment by angelozerr** [comment]
@marijnh I have used your last version of ternjs 0.9.0 and errors seems not occurs!

Many thanks!

@piotrtomiak I have pushed inside tern.java last version of tern + acorn. Is it OK for you. If it's OK, I will close this issue.

**Comment by marijnh** [comment]
That's great to hear.

**Comment by piotrtomiak** [comment]
> @piotrtomiak I have pushed inside tern.java last version of tern + acorn. Is it OK for you. If it's OK, I will close this issue.

I am not able to test it yet, but I believe it is fixed, it seemed to be the same issue as you had.
