### ISSUE TITLE
update with text containing '..' at any position crashes the server

### ISSUE THREAD

**Issue by tststs** [marijnh/tern#493]
@post(JSON.stringify
      files: [
          type: 'full'
          name: file
          text: text
      ]
    )

If text contains '..' at any position, the server crashes.

E.g.:

"var ts = new TSTSTS(); ts.help(); ts.."

Here is the output:

/Users/xxx/github/atom-ternjs/node_modules/tern/lib/infer.js:1174 return inferExprVisitornode.type; ^ TypeError: undefined is not a function at infer (/Users/xxx/github/atom-ternjs/node_modules/tern/lib/infer.js:1174:39) at Object.walk.make.Expression (/Users/xxx/github/atom-ternjs/node_modules/tern/lib/infer.js:1179:7) at c (/Users/xxx/github/atom-ternjs/node_modules/tern/node_modules/acorn/util/walk.js:60:37) at Object.base.ExpressionStatement (/Users/xxx/github/atom-ternjs/node_modules/tern/node_modules/acorn/util/walk.js:176:5) at c (/Users/xxx/github/atom-ternjs/node_modules/tern/node_modules/acorn/util/walk.js:60:37) at Object.skipThrough [as Statement] (/Users/xxx/github/atom-ternjs/node_modules/tern/node_modules/acorn/util/walk.js:163:39) at c (/Users/xxx/github/atom-ternjs/node_modules/tern/node_modules/acorn/util/walk.js:60:37) at Object.base.Program.base.BlockStatement (/Users/xxx/github/atom-ternjs/node_modules/tern/node_modules/acorn/util/walk.js:171:7) at c (/Users/xxx/github/atom-ternjs/node_modules/tern/node_modules/acorn/util/walk.js:60:37) at Object.walk.make.ScopeBody (/Users/xxx/github/atom-ternjs/node_modules/tern/lib/infer.js:1225:43)

Thx
tststs

**Comment by marijnh** [comment]
This was actually an Acorn bug, which was fixed in attached patch. I'll bring out an Acorn release and bump the version Tern depends on soon. For now, getting Acorn from git would work around the issue.
