### ISSUE TITLE
[requirejs plugin] Hang when using protocol relative URLs

### ISSUE THREAD

**Issue by MarcelGerber** [marijnh/tern#495]
(adobe/brackets#10566)
So Tern with the RequireJS plugin loaded hangs for exactly 8 seconds in [this project](https://drive.google.com/file/d/0B_cXwlY8JUfILTJEVzRaZVRCX3M/view?usp=sharing) (on either JS file).

`git bisect` pointed me to ed952de, so that's why I did some further debugging in that section.
The `path.join` function is always called from [`requirejs.js:155`](https://github.com/marijnh/tern/blob/master/plugin/requirejs.js#L155).

I also replaced `path.join` with this logging function:
``` js
    join: function(a, b) {
      var ret;
      if (b && b.charAt(0) != ".") ret = b;
      else if (a && b) ret = a + "/" + b;
      else ret = (a || "") + (b || "");
      console.log({a: a, b: b, ret: ret, ret1: b, ret2: a + "/" + b, ret3: (a || "") + (b || "")}, new Date().toLocaleTimeString());
      return ret;
    }
```

And this is what I got:
![image](https://cloud.githubusercontent.com/assets/2641501/6199091/f338d428-b42d-11e4-8387-7bc4699c5366.png)

__Important__:
As you can see in adobe/brackets#10566, simply changing both URLs in `main.js`' `paths` to use the `http://` protocol fixes this issue!

**Comment by marijnh** [comment]
I couldn't get this to hang—I guess the effect is related to the way Brackets' `getFile` callback handles URLs. Did you get a profile of those 8 seconds? What is the code doing there?

Looking at the `join` function, it seems paths starting with `//` will be returned unchanged, which is about right. What does your `getFile` implementation do with such paths?

**Comment by MarcelGerber** [comment]
Yeah you're right, it's an issue with Brackets' implementation of `getFile`.
Closing.
