### ISSUE TITLE
RangeError: Maximum call stack size exceeded at Array.every

### ISSUE THREAD

**Issue by tststs** [marijnh/tern#497]
Hi there,

this is the only file loaded and completions is called from any point.

```
var DTaiko = function () {

	this.init = function () {


	};
};

$(function () {

	dTaiko = new DTaiko();
	dTaiko.init();
});
```

If <code>this.init = function () { ... };</code> is removed, everything works as expected.

atom-ternjs
RangeError: Maximum call stack size exceeded at Array.every (native) at similarType (/Users/tobiasschubert/github/atom-ternjs/node_modules/tern/lib/infer.js:229:19) at similarAVal (/Users/tobiasschubert/github/atom-ternjs/node_modules/tern/lib/infer.js:204:12) at similarType (/Users/tobiasschubert/github/atom-ternjs/node_modules/tern/lib/infer.js:221:32) at similarAVal (/Users/tobiasschubert/github/atom-ternjs/node_modules/tern/lib/infer.js:204:12) at similarType (/Users/tobiasschubert/github/atom-ternjs/node_modules/tern/lib/infer.js:230:48) at similarAVal (/Users/tobiasschubert/github/atom-ternjs/node_modules/tern/lib/infer.js:204:12) at similarType (/Users/tobiasschubert/github/atom-ternjs/node_modules/tern/lib/infer.js:221:32) at similarAVal (/Users/tobiasschubert/github/atom-ternjs/node_modules/tern/lib/infer.js:204:12) at similarType (/Users/tobiasschubert/github/atom-ternjs/node_modules/tern/lib/infer.js:230:48)

Thx,
tststs

**Comment by angelozerr** [comment]
Perhaps it's teh same issue than https://github.com/marijnh/tern/issues/492 ?

**Comment by marijnh** [comment]
If I paste this into the demo and complete, no errors are produced. Could you be more specific on how you're getting things to crash?

**Comment by marijnh** [comment]
Attached patch might help -- I wasn't able to reproduce the issue, but given the stack trace I could come up with a theory of what went wrong.

**Comment by tststs** [comment]
Sorry, my fault. I was using release 0.8.0.
if i use the latest version directly from the repo, the error doesn't occurs.

thx
tststs
