### ISSUE TITLE
Go to definition for require in nodejs

### ISSUE THREAD

**Issue by madhavan020985** [marijnh/tern#498]
Many times, when i import external libraries via CommonJs, i would like to see the object properties for imported objects.
for example, i would like to know the internals of say, Connection object in this case
````javascript
var Connection = require('ssh2');  
````
I didn't see support in ternjs via emacs, so i wrote this tiny lib file. On function/command invocation from a line tha contains require statement, the lib takes the imported module's name and go to the "module.exports" assignment statement in ssh2 module's entry point, possibly index.js:::::
````lisp
(require 's)
(require 'json)
(defun last-index-of (regex str &optional ignore-case)
  (let ((start 0)
        (case-fold-search ignore-case)
        idx)
    (while (string-match regex str start)
      (setq idx (match-beginning 0))
      (setq start (match-end 0)))
    idx))

(defun tern-goto-def-require ()
  (interactive)
   (defvar start-index 0)
   (defvar end-index 0)
   (setq myStr (thing-at-point 'line))
   (setq start-index  (s-index-of "require" myStr))
   (when start-index
       (setq start-index (+ start-index 9))
       (setq last-index (last-index-of "\'" myStr))
       (setq lib (substring myStr start-index last-index))
       (setq basedir default-directory)
       (setq projectdir (concat basedir "node_modules" "/" lib)) 
       (setq conffile (concat projectdir "/" "package.json"))
       (setq mainfile (cdr (assoc 'main (json-read-file conffile))))
       (cond ((s-blank? mainfile) (setq mainfile "index.js"))
	     (t (setq indexfile (concat projectdir (substring mainfile 1)))))
       (unless (s-ends-with? ".js" indexfile) 
	 (setq indexfile (concat indexfile ".js")))
       (switch-to-buffer (find-file indexfile))
       (goto-char (search-forward "module.exports")))
;;       (message indexfile)
   (unless start-index
     (message "the current line doesn't import any module")))
````
Marij, is this feature already present in ternjs. if not, it is worth considering to add it in this form (or) in any convenient form.

**Comment by marijnh** [comment]
I think patch ba28ef09771 will help -- it allows you to press Alt-. after a parenthesized expression. So if you put the cursor after `require("...")`, you can jump to the required file (or the actual definition, if it assigns to `module.exports`). Does that solve your problem?
