### ISSUE TITLE
selectName() + CodeMirror selects identical names and generate additional cursors

### ISSUE THREAD

**Issue by gooddaytoday** [marijnh/tern#503]
selectName() in CodeMirror selects identical names and generate additional cursors after pressing one of arrow keys. 

For example, if you select 3 identifiers, after pressing arrow key you will earn three cursors. And than just write code three times faster (joke).

You can try here: http://codemirror.net/demo/tern.html

Ctrl+. - combination for selecting

**Comment by marijnh** [comment]
Yes, you have described the behavior of this command accurately. I am not sure where the bug is, though. If you don't know how to get rid of multiple selections, press Esc or click somewhere.
