### ISSUE TITLE
Tern linter query type API

### ISSUE THREAD

**Issue by angelozerr** [marijnh/tern#504]
I have implemented several linter with tern that I use in tern.java https://github.com/angelozerr/tern.java/wiki/Tern-Linter

 * Lint which is a semantic linter. See https://github.com/angelozerr/tern-lint
 * ESLint. See https://github.com/angelozerr/tern-eslint
 * JSHint. See https://github.com/angelozerr/tern-jshint
 * JSCS. ( JSCS is JavaScript Code Style checker http://jscs.info/ ). See https://github.com/angelozerr/tern-jscs

Each tern linter defines a query type (lint, eslint, jshint, jscs) and returns the same JSON messages result. So it's possible to use several linters. To do in tern.java that I loop for each linters and call tern server with the well query type. In other words I call for a file N tilmes the tern server (where N is a number of linters).

But I think it should be very clean to call one time the tern server with a query type (ex : linter) and this query type loop for each linter to aggregate linter messages.

So I tell me if tern.js could provide a tern linter query type which does that. If you like this idea I could create a PR.

@marijnh tell me if you need more informationss.

**Comment by marijnh** [comment]
Plugins can add their own query types (as you are aware). Why don't you put this into a plugin?

**Comment by angelozerr** [comment]
> Plugins can add their own query types (as you are aware). Why don't you put this into a plugin?

Yes I can do that, but it requires that user will have to add 2 tern plugins to use the linter : 

 * the API tern linter
 * the Implementation (ESLint, JSHint, etc) linter.

I told me if tern.js could host this API tern linter, it should be easier for user and it will give a contract for new linter implementation.

**Comment by marijnh** [comment]
Well, my answer is still that linting is outside of the scope of my library, so no.

It would be useful to be able to specify dependencies between plugins (and definitions json files). If you want to work on that, that'd be helpful.

**Comment by angelozerr** [comment]
> Well, my answer is still that linting is outside of the scope of my library, so no.

Ok. So I will create a linter API tern plugin.

> It would be useful to be able to specify dependencies between plugins (and definitions json files). If you want to work on that, that'd be helpful.

You mean https://github.com/marijnh/tern/issues/424 ? If it's that, yes I have the intention to do it, I'm very busy with tern linter support but after I will work on it. In tern.java I have already those dependencies in https://github.com/angelozerr/tern.java/tree/master/core/ternjs/metadata.

For instance if you wish to use ecma6, ecma5 is required. The Eclipse user select with an UI ecma6 and ecma5 is selected automaticly. To describe this dependency, I use https://github.com/angelozerr/tern.java/blob/master/core/ternjs/metadata/ecma.metadata.json#L9 : 

```json
{
 "name": "ecma",
 ...
 "dependencies": {
  "6": [
   "ecma5"
  ]
...
```

Is this feature you are talking?
