### ISSUE TITLE
ImportError: No module named site

### ISSUE THREAD

**Issue by noscripter** [marijnh/tern#505]
When I edit .js file with macvim, it crashes with the following output, wonder how to fix it?

**Comment by marijnh** [comment]
That's a python error, but tern.py never tries to import anything named `site`. So it might be another plugin causing this.

**Comment by noscripter** [comment]
yes, that's exactly the reason, I found that too, refer to <https://code.google.com/p/macvim/issues/detail?id=392> for specific steps to fix this error.
