### ISSUE TITLE
Completion doesn't work with referenced Object literal

### ISSUE THREAD

**Issue by angelozerr** [marijnh/tern#508]
Tern supports Object literal with this case : 

```javascript
requirejs.config({
  // here Ctrl+Space show baseUrl
});
```

But if you declare the object literal in a var, it doesn't work : 

```javascript
var config = {
  // PROBLEM : here Ctrl+Space doesn't show baseUrl
}
requirejs.config(config);
```

**Comment by marijnh** [comment]
Patches 71a716 and c5db7a7231 should resolve this.

**Comment by angelozerr** [comment]
@marijnh I have tested your patch and it works well if you type one character : 

```javascript
var config = {
  c // here Ctrl+Space show callback, config
}
requirejs.config(config);
```

but if you try to open the completion without characters, it doesn't work : 

```javascript
var config = {
  // PROBLEM : here Ctrl+Space doesn't show callback, etc
}
requirejs.config(config);
```

**Comment by marijnh** [comment]
This works for me (in the web demo).

**Comment by angelozerr** [comment]
The web demo http://ternjs.net/doc/demo.html doesn't work because of bad acorn path.

**Comment by marijnh** [comment]
Oops, forgot to upgrade Acorn on my server. Should be better now.

**Comment by angelozerr** [comment]
> Oops, forgot to upgrade Acorn on my server. Should be better now.

Thanks @marijnh!

Indeed it works with HTML demo but in my case (execute tern inside node.js + lineCharPositions=false with Eclipse) it doesn't work. I will study why there is this problem.

**Comment by angelozerr** [comment]
@marijnh I have found my problem. It's because in my case query.omitObjectPrototype is set to true.

So I don't execute th ecode https://github.com/marijnh/tern/blob/master/lib/tern.js#L694 because my completion is not empty although with tern demo, query.omitObjectPrototype is set to false.

To fix the problem, I think we should not provide methods of prototype (even if omitObjectPrototype  is set to true) for object literal. See my PR https://github.com/marijnh/tern/pull/520
