### ISSUE TITLE
Tern JS can't complete global functions

### ISSUE THREAD

**Issue by StefanICT** [marijnh/tern#516]
Example:

```javascript
/**
 * Detects if the given argument can be called * as a function
 */
function isCallable() {
     return fn && fn instanceof Function;
}
```

Tern doesn't complete this and given the documentation, but when I change it to:

```javascript
/** 
* Detects if the given argument can be called * as a function
*/
var isCallable = function () {
    return fn && fn instanceof Function;
};  
```

And call it like

````
this.is...
````

Tern js shows me the documentation and the possible autocompletions. Why can't I just type the name of the function? Without this?

**Comment by marijnh** [comment]
Tern most certainly **can** complete global functions, as is trivially verified using the [online demo](http://ternjs.net/doc/demo.html). You probably have some other problem.

**Comment by StefanICT** [comment]
I got it working now, but still it only auto shows the documentation when I use this. before a global method. When I use TernDef on the function is shows the documentation
