### ISSUE TITLE
Working with modified buffers

### ISSUE THREAD

**Issue by eranif** [marijnh/tern#517]
Hi,
First thanks for this great project.
I am working into integrating it into [CodeLite IDE](http://codelite.org)

I did encounter one issue, how is the JSON protocol suppose to work with modified buffers?
i.e. the API requires files, however, the current buffer is modified and obliviously the line being edit in many cases will be out of the saved file buffer size, or not exist at all.

Does the API support passing the "unsaved buffer" ?
(sorry for reporting this here, could not find any forum to post it)

My current workaround is: save the modified buffer into a temp file and pass this file to tern.

**Comment by marijnh** [comment]
Include changed buffers in the `files` part of the request. See for example the [CodeMirror addon](http://codemirror.net/addon/tern/tern.js). If you want to support sending partial files, when a big file is being edited, things get a little more complex, but the [docs](http://ternjs.net/doc/manual.html#protocol) should give you an idea of what the protocol can do.
