### ISSUE TITLE
Jump to definition does not work on objects defined as property on window

### ISSUE THREAD

**Issue by vikynandha** [marijnh/tern#518]
In my tern set up in emacs, this code works fine when I do `M-.` on util.foo:
```js
var obj = {};
obj.foo = function() {
    return true;
};

obj.foo();
```

But when I do the same on the following, it says "No definition found."

```js
window.obj = {};
obj.foo = function() {
    return true;
};

obj.foo();
```

I tried making each refernce to `obj` as `window.obj`. Doesn't seem to help. Am I missing something?

**Comment by vikynandha** [comment]
I just realized that it works on the online demo.

BTW, I tried using a new variable as namespace instead of window, and it works fine:

```js
var ns = {};
ns.obj = {};
ns.obj.foo = function() {
  return true;
};

ns.obj.foo();
```

**Comment by marijnh** [comment]
If I paste your example into a .js file and open it in emacs, I can Alt-. from `foo` on the last line to the definition of `obj.foo` just fine.

**Comment by angelozerr** [comment]
See my answer at http://stackoverflow.com/questions/29450235/jump-to-definition-does-not-work-on-objects-defined-as-property-on-window/30637975#30637975

**Comment by vikynandha** [comment]
@angelozerr, Great! It works. Thanks.
