### ISSUE TITLE
[emacs plugin] Support completion in nodejs-repl

### ISSUE THREAD

**Issue by conorbev** [marijnh/tern#521]
I am using tern successfully in Emacs with js2-mode.

I also tried using [nodejs-repl](https://github.com/abicky/nodejs-repl.el) 

The repl is "working" but I'm not seeing any completion candidates. I enabled tern-mode in the REPL buffer and when I try to complete I see the following in *Messages*:

Tern mode enabled
tern-run-query: Wrong type argument: arrayp, nil

Any ideas how to get this to work?

Thanks!

**Comment by marijnh** [comment]
Since such a repl buffer isn't a regular JavaScript file, you'd have to write a different minor mode for it. This is outside of the scope of this repository, but it's probably not terribly hard if you reuse pieces from my tern.el.
