### ISSUE TITLE
Can't install tern

### ISSUE THREAD

**Issue by bryan-kramer** [marijnh/tern#522]
% npm install tern
npm http GET https://registry.npmjs.org/tern
npm http 304 https://registry.npmjs.org/tern
npm http GET https://registry.npmjs.org/minimatch
npm http GET https://registry.npmjs.org/typescript/1.0.1
npm http GET https://registry.npmjs.org/acorn
npm http GET https://registry.npmjs.org/glob
npm http 304 https://registry.npmjs.org/minimatch
npm http 304 https://registry.npmjs.org/typescript/1.0.1
npm http 304 https://registry.npmjs.org/acorn
npm ERR! Error: No compatible version found: acorn@'^1.0.1'
npm ERR! Valid install targets:
npm ERR! ["0.0.1","0.1.0","0.2.0","0.3.0","0.3.1","0.4.0","0.4.2","0.5.0","0.6.0","0.7.0","0.8.0","0.9.0","0.10.0","0.11.0","0.12.0","1.0.0","1.0.1","1.0.3"]
npm ERR!     at installTargetsError (/usr/local/lib/node_modules/npm/lib/cache.js:682:10)
npm ERR!     at /usr/local/lib/node_modules/npm/lib/cache.js:597:10
npm ERR!     at saved (/usr/local/lib/node_modules/npm/node_modules/npm-registry-client/lib/get.js:138:7)
npm ERR!     at Object.oncomplete (fs.js:93:15)
npm ERR! If you need help, you may report this log at:
npm ERR!     <http://github.com/isaacs/npm/issues>
npm ERR! or email it to:
npm ERR!     <npm-@googlegroups.com>

npm ERR! System Linux 3.19.3-200.fc21.x86_64
npm ERR! command "node" "/usr/local/bin/npm" "install" "tern"
npm ERR! cwd /home/bryan
npm ERR! node -v v0.9.12-pre
npm ERR! npm -v 1.2.14
npm http 304 https://registry.npmjs.org/glob
npm ERR! 
npm ERR! Additional logging details can be found in:
npm ERR!     /home/bryan/npm-debug.log
npm ERR! not ok code 0

**Comment by marijnh** [comment]
Could it be that your npm is old(ish)? I believe support for `^` notation in dependency versions was added not so very long ago. Try upgrading npm, it might solve this.

**Comment by bryan-kramer** [comment]
You're right, sorry. I was assuming npm was being updated by the package manager but it turns out that it was separately installed and not updating. Fixed now.

Thanks
