### ISSUE TITLE
RangeError: Maximum call stack size exceeded at extend.hasProp 

### ISSUE THREAD

**Issue by int3h** [marijnh/tern#523]
This seems to be similar to #492 and #497, but it seems to be caused by a different code path, and is still occurring in the latest (git master) version of tern (v0.10.1 according to the package.json).

When getting completions, I get the following error output from Tern:

```
RangeError: Maximum call stack size exceeded at extend.hasProp 
(~/.atom/packages/atom-ternjs/node_modules/tern/lib/infer.js:514:22) at extend.getProp 
(~/.atom/packages/atom-ternjs/node_modules/tern/lib/infer.js:544:24) at Object.extend.computedPropType 
(~/.atom/packages/atom-ternjs/node_modules/tern/lib/infer.js:144:42) at Object.extend.makeupType 
(~/.atom/packages/atom-ternjs/node_modules/tern/lib/infer.js:150:27) at Object.extend.toString 
(~/.atom/packages/atom-ternjs/node_modules/tern/lib/infer.js:135:56) at exports.toString 
(~/.atom/packages/atom-ternjs/node_modules/tern/lib/infer.js:26:48) at extend.toString 
(~/.atom/packages/atom-ternjs/node_modules/tern/lib/infer.js:677:20) at exports.toString 
(~/.atom/packages/atom-ternjs/node_modules/tern/lib/infer.js:26:48) at ~/.atom/packages/atom-ternjs/node_modules/tern/lib/infer.js:139:51 at Array.map (native)
```

As you can see, I'm using tern via the [atom-ternjs](//github.com/tststs/atom-ternjs) package, but I don't believe that's the cause of the error.

The code I'm able to reproduce this on is simple:

```JavaScript
'use strict';

var util = require('util');
var _ = require('lodash');


function ClientError(message, friendlyMessage, socket, ack) {
    Error.call(this);

    _.   // <-- error comes after typing the '.' here

    this.message = message;
    this.socket
}
util.inherits(ClientError, Error);
```

I'm using the module library, and Node.js' built-in util module, but what you see is the entire file. On the line indicated within the `ClientError` function, when I type `_.`, the error occurs (atom-ternjs does a `completions` query for that cursor position, which is the trigger.)

My tern config file is:
```JSON
{
  "libs": [
    "ecma5"
  ],
  "loadEagerly": [

  ],
  "plugins": {
    "complete_strings": {},
    "doc_comment": {
     "fullDocs": true
    },
    "node": {}
  }
}
```

If it matters, my atom-ternjs config as follows (with everything else left at defaults):
```CSON
"atom-ternjs":
    origins: false
    urls: false
```

**Comment by marijnh** [comment]
I wasn't able to reproduce this -- if I set up a project like that, I can complete the properties of `_` without problem. (Though I'm using Emacs, not Atom).

**Comment by int3h** [comment]
My steps to reproduce are:

1. Create a new folder
2. Create a `package.json` with content as below
3. `npm install` in this folder to install lodash
4. Create a `.tern-project` file as above
5. In Atom, create a new JavaScript file in your node package's directory
6. Insert the line `var _ = require('lodash');`
5. On the next line, type `_.`, and you should get the RangeError exception on stderr from the tern server

`package.json`:
```json
{
  "name": "tern-test",
  "version": "1.0.0",
  "description": "Test for tern+lodash incompatibility",
  "private": true,
  "dependencies": {
    "lodash": "latest"
  },
  "devDependencies": {}
}
```

I added logging of all the queries sent to to the tern server by atom-ternjs, and this was the full output from doing the above steps:

```json
{"files":[{"type":"full","name":"~/Desktop/tern_test/lib/test.js","text":"'use strict';\n\nvar _ = require('lodash');\n\n_"}]}
atom-ternjs-client.coffee:119 {"query":{"type":"completions","file":"~/Desktop/tern_test/lib/test.js","end":{"line":4,"ch":1},"types":true,"includeKeywords":true,"sort":true,"guess":true,"docs":true,"urls":true,"origins":true,"lineCharPositions":true,"caseInsensitive":true}}
atom-ternjs-client.coffee:119 {"files":[{"type":"full","name":"~/Desktop/tern_test/lib/test.js","text":"'use strict';\n\nvar _ = require('lodash');\n\n_."}]}
atom-ternjs-client.coffee:119 {"query":{"type":"completions","file":"~/Desktop/tern_test/lib/test.js","end":{"line":4,"ch":2},"types":true,"includeKeywords":true,"sort":true,"guess":true,"docs":true,"urls":true,"origins":true,"lineCharPositions":true,"caseInsensitive":true}}
```

This is the code atom-ternjs uses to start the Tern server:

```coffee
command = path.resolve __dirname, '../node_modules/.bin/tern'
args = ['--persistent', '--no-port-file', '--verbose']
options =
  cwd: atom.project.getDirectories()[0].path
stdout = (output) ->
  output = output.split(' ')
  port = parseInt(output[output.length - 1])
  return if isNaN(port)
  callback port
```

(I'm not associated with the atom-ternjs package author(s) at all, just a user of it.)

**Comment by int3h** [comment]
I should also add that I can't seem to get the `condense` utility to spit out a legal JSON type definition for lodash. I've tried running it on lodash's `index.js` file directly, on the modularized files within lodash (`lodash/*.js`, but remove `index.js`), on all the subfiles within lodash (`lodash/*/*.js`), appending `+` to some/most/all of those files, enabling/disabling the `node` and/or `doc_comment` plugins for tern, using `--name _`, etc.

The result is either that the JSON type definition has nothing included, or that the resulting type definition crashes tern when used in the `libs` project config option and/or the `modules` option of the `node` plugin options in the project config.

If you can generate the type definition JSON and upload it as a gist or similar, I'd be happy to try it out!

**Comment by Rukenshia** [comment]
I get a similar issue when i open the node-mysql package (using atom-ternjs).

**Comment by marijnh** [comment]
Attached patch should help. I'm still not sure why this could be reproduced in Atom but not other editors, but installing Atom did indeed yield that error.

(The type for lodash still gets inferred as some weird recursive thing, so don't expect useful completions there, but at least it stopped crashing.)

**Comment by Rukenshia** [comment]
Still not working (using atom-ternjs, updated ternjs manually.

Error:
```
Maximum call stack size exceeded at C:\Users\Me\atom\packages\atom-ternjs\node_modules\tern\lib\infer.js 
at Obj.purge (C:\Users\Me\atom\packages\atom-ternjs\node_modules\tern\lib\infer.js:1327:11) 
at Object.AVal.purge (C:\Users\Me\atom\packages\atom-ternjs\node_modules\tern\lib\infer.js:1309:14) 
at Obj.purge (C:\Users\Me\atom\packages\atom-ternjs\node_modules\tern\lib\infer.js:1329:10) 
at Object.AVal.purge (C:\Users\Me\atom\packages\atom-ternjs\node_modules\tern\lib\infer.js:1309:14) 
at Obj.purge (C:\Users\Me\atom\packages\atom-ternjs\node_modules\tern\lib\infer.js:1329:10) 
at Object.AVal.purge (C:\Users\Me\atom\packages\atom-ternjs\node_modules\tern\lib\infer.js:1309:14) 
at Obj.purge (C:\Users\Me\atom\packages\atom-ternjs\node_modules\tern\lib\infer.js:1329:10) 
at Object.AVal.purge (C:\Users\Me\atom\packages\atom-ternjs\node_modules\tern\lib\infer.js:1309:14) 
at Obj.purge (C:\Users\Me\atom\packages\atom-ternjs\node_modules\tern\lib\infer.js:1329:10)
```

**Comment by marijnh** [comment]
That's a different infinite recursion. I wonder what it is about Atom that keeps exposing these bugs. Do you have instructions on how to reproduce this new one? (The steps outlined before no longer trigger an error for me.)

**Comment by Rukenshia** [comment]
Somehow worked again for me when I started my computer today. Issue can be closed
