### ISSUE TITLE
Completion for object properties inside a loop for

### ISSUE THREAD

**Issue by angelozerr** [marijnh/tern#530]
I don't know if it's easy but it should be cool if tern could support completion for object properties used in a for loop like this :

```javascript
var obj = {"aa": {"x" : 10, "y" : 10}}
for (var key in obj) {
	obj[key]. // here Ctrl+Space shows x and y properties
}
```

**Comment by marijnh** [comment]
Attached patch should work (it doesn't take the loop into account, it just falls back to a random other property when trying to guess a type for a dynamic property that has no type).

**Comment by angelozerr** [comment]
Works like a charm, thanks @marijnh !
