### ISSUE TITLE
local scope variables

### ISSUE THREAD

**Issue by hushicai** [marijnh/tern#533]
excuse me, but is there any api to find out local scope variables?

code:
```
define(
    function (require) {
        var test = {
            a: 1,
            b: 2
        };

        var xx = 1;

        return test;
    }
);
```

i want to find out the local varible `xx`, can i?

**Comment by marijnh** [comment]
There is no API in the server interface for this, but you could write a plugin that adds one. See the `defineQueryType` function in `tern.js` for defining new query types, and see the `Scope` object and the way the AST searching functions (for example `infer.findExpressionAt`) return one in the `state` proper of their return value for an approach to getting at this scope.
