### ISSUE TITLE
JSDoc comments overridden by 'interpreted usage'

### ISSUE THREAD

**Issue by NiloCK** [marijnh/tern#536]
A function decorated with JSDoc comments is correctly parsed, but if the same function is used such that interpreting its signature via usage alone disagrees with the signature extrapolated from the JSDoc comments, then this interpreted signature 'wins' and is applied for future autocompletes.

The resolution between these two conflicting signatures should probably go the other way: user supplied documentation should be authoritative in determining the signature of a function.

I'm not satisfied with how clearly I've described this, but the attached screenshots should clarify. These shots are from [atom-ternjs](https://github.com/tststs/atom-ternjs), where I originally posted this issue. The author forwarded me here.

1: Correct interpretation of JSDoc. Note the type of the action parameter. The function is not used anywhere in the project, just declared and defined here.
![correct-nousage](https://cloud.githubusercontent.com/assets/10780590/7374132/1794a7aa-edab-11e4-87d7-47a117a3bb78.png)

2: Incorrect interpretations which combine usage of the function with reading the JSDoc comment. Again note the expected type of the action parameter.
![tern2](https://cloud.githubusercontent.com/assets/10780590/7374311/0fb38cbc-edac-11e4-972b-d57bbc48d21c.png)
![tern3](https://cloud.githubusercontent.com/assets/10780590/7374312/0fbf6abe-edac-11e4-87e5-13f5c4426d70.png)

Further odd behavior occurs if, for example, a `number` is passed in as the `action` parameter, or if combinations of the different usages are used.

**Comment by marijnh** [comment]
Configure the `doc_comment` plugin like this in your `.tern-project`:

```json
{
  "plugins": {"doc_comment": {"strong": true}}
}
```
