### ISSUE TITLE
Dynamically defineProperty

### ISSUE THREAD

**Issue by dani-h** [marijnh/tern#539]
I know support for Object.defineProperty/ies was recently implemented in Tern and I'm wondering if that could be extended to support dynamic monkey patching. 
 
```javascript
  var obj = {}
  var properties_arr = ['foo', 'bar', 'baz']
  properties_arr.forEach(function(prop) {
    Object.defineProperty(obj, prop, {
      get: function() {
       //todo
      },
      set: function(value) {
        //todo
      }
    })
  })
```

**Comment by marijnh** [comment]
Tern does not track the content of string values (or arrays of strings), only their type. As such, barring a rewrite or a major change in architecture, it is not going to be able to see through the code in your example.

**Comment by dani-h** [comment]
Ok thanks
