### ISSUE TITLE
tern-ac-complete is possibly inconsistent with auto-complete and single completions

### ISSUE THREAD

**Issue by whitlockjc** [marijnh/tern#540]
Whenever I invoke auto-complete and there is only one possible completion, that completion is automatically chosen and its completion is inserted within my buffer.  _(Documentation for the item continues to display until I type.)_  With tern-ac-complete, this is not the case and the single completion is displayed as the only candidate but I have to manually key enter/tab to accept the completion.  It would be nice if it behaved like auto-complete, or if there was a configurable option to automatically chose the completion when there is only one candidate for completion.  _(Displaying documentation for the completion until I type would be slick as well.)_

Now, I'm fairly new to Tern.js support in Emacs so I could be completely wrong, which is why I said _"possibly inconsistent"_, and if that is the case just let me know.

Thoughts?

**Comment by marijnh** [comment]
I'm sure there is a way to configure this, but it is probably in the completion framework, not in Tern. (I never used tern-ac-complete, so I'm not 100% sure, but I assume it also leaves the user interface stuff to the `auto-complete` package).
