### ISSUE TITLE
RangeError: Maximum call stack size exceeded

### ISSUE THREAD

**Issue by dvalle-nearsoft** [marijnh/tern#541]
# Range Error on Atom - tern and also on sublime text
Hello, my tern in atom and sublime text is producing the same error, this happens when i invoke a self made module, ei:

```
var LinkedList = require('../src/linkedList').LinkedList;
list = new LinkedList('hello');
```
when it tries to autocomplete on list, the error keeps popping up and it's really annoying

thanks 

>
RangeError: Maximum call stack size exceeded at extend.toString (/home/dvalle/atom-ternjs/node_modules/tern/lib/infer.js:508:23) at exports.toString (/home/dvalle/atom-ternjs/node_modules/tern/lib/infer.js:26:48) at Object.extend.toString (/home/dvalle/atom-ternjs/node_modules/tern/lib/infer.js:136:42) at exports.toString (/home/dvalle/atom-ternjs/node_modules/tern/lib/infer.js:26:48) at extend.toString (/home/dvalle/atom-ternjs/node_modules/tern/lib/infer.js:515:36) at exports.toString (/home/dvalle/atom-ternjs/node_modules/tern/lib/infer.js:26:48) at Object.extend.toString (/home/dvalle/atom-ternjs/node_modules/tern/lib/infer.js:136:42) at exports.toString (/home/dvalle/atom-ternjs/node_modules/tern/lib/infer.js:26:48) at extend.toString (/home/dvalle/atom-ternjs/node_modules/tern/lib/infer.js:515:36) at exports.toString (/home/dvalle/atom-ternjs/node_modules/tern/lib/infer.js:26:48)

**Comment by marijnh** [comment]
Is this still happening with version 0.11?

**Comment by danvalang** [comment]
Yes, just updated it to 0.11.1 and still happens

**Comment by dvalle-nearsoft** [comment]
also, i looked into it, the official sublime addon gives this error but the Tern addon, the one that uses pyV8 works alright

**Comment by marijnh** [comment]
Okay, I guess my last patch must have missed a case then. Can you reduce the code that triggers this to its minimum, and submit enough information for me to reproduce the issue?

**Comment by dvalle-nearsoft** [comment]
https://github.com/dvalle-nearsoft/dataStructures 
In this repo, using atom (atom-tern) or subilme (tern_for_sublime) editor with  when trying to autocomplete on the list object on the following code:

```
var LinkedList = require('../src/linkedList').LinkedList;
list = LinkedList('fubar');
```

the error triggers when it tries to autocomplete the ``list`` object.

My system is Ubuntu 14.04 with node v0.12.2 , i don't know if it has anything to do with this, but it doesn't affect to mention it.

**Comment by marijnh** [comment]
Strange. Completions work fine for me in that context. I cloned the repository, added a `.tern-project` with `{ "plugins": {"node": {}} }` in it, and created a file `foo.js` with the code you gave. If I do, in Sublime Text, `list.` and then alt-/ to pop up completions, I get appropriate completions for a linked list object, and no crash.

**Comment by dvalle-nearsoft** [comment]
![image](https://cloud.githubusercontent.com/assets/12420374/7921471/8aebfcca-085a-11e5-8cef-2ba80e67dc56.png)
Maybe this would help?

**Comment by marijnh** [comment]
Yes, that did help. I was able to reproduce the issue in that test file, though my own file based on the snippet you gave earlier did not trigger it.

Attached patch fixes it for me, but please test it on your side as well.

**Comment by dvalle-nearsoft** [comment]
Yes that fixed it, thanks a lot
