### ISSUE TITLE
Additional signatures for jQuery def

### ISSUE THREAD

**Issue by amiuhle** [marijnh/tern#543]
I'm using @angelozerr's [tern-lint](https://github.com/angelozerr/tern-lint) and have jquery configured as a library in my `.tern-project`.

Unfortunately, the jquery def only supports the `jQuery( selector [, context ] )` function, which means I get errors when supplying a callback function or an `Element`:

```js
$(function() {
  // do something
}
// => Invalid argument at 1: cannot convert from Function.prototype to String.prototype
```

Is it possible to either
* additionally add `jQuery( html [, ownerDocument ] )` and `jQuery( callback )`?
* change the current signature to something more generic like
  `fn(selectorOrCallback: ?, context?: frameElement) -> jQuery.fn`

**Comment by didoarellano** [comment]
Tern doesn't support overloaded functions, unfortunately. You'll run into issues auto-completing jQuery's getter/setter methods (css, attr, etc.) as well because of this.

**Comment by angelozerr** [comment]
@amiuhle there is the same issue with angular and tern-lint https://github.com/angelozerr/tern-lint/issues/39

Please create an issue at https://github.com/angelozerr/tern-lint/issues/ for your case and I will try to support it when I will find time. Thanks

**Comment by amiuhle** [comment]
@didoarellano But then defining the moethods as generic as possible would make sense, wouldn't it? If you can pass multiple values as the fist parameter, the signature shouldn't be restricted to a string.

@angelozerr Thanks, will do that.
