### ISSUE TITLE
Does tern resolve custom require functions?

### ISSUE THREAD

**Issue by myshov** [marijnh/tern#545]
Marijn, Hello! First of all thank you for your great contribution to js-community, really.
I have a question. Does tern resolve custom require functions in node.js? I mean that case when, for avoiding stuff like this:
```JavaScript
var lib = require('../.../../../../../../superlib.js');
```
is used pretty common pattern like this:

```JavaScript
var projectDir = __dirname;

module.exports = GLOBAL.projRequire = function(module) {
  return require(projectDir + module);
}
```
More information can be found for example [here](http://stackoverflow.com/a/10865271/1675347)
So after that it's possible require js-file relative of the root of the project with this code:
```Javascript
var lib = projRequire('superlib.js');
```
It seems out of the box tern doesn't support this kind of thing - completion, and jump to definition doesn't work if it's defined that way. Maybe already is there some setting regarding this?

**Comment by marijnh** [comment]
Nope, Tern does not track the content of string variables, and thus does not figure out what a concatenated module name stands for.

**Comment by myshov** [comment]
@marijnh Is it possible to implent this kind of feature with config settings like this?
```JavaScript
  "plugins": {
    "node": {
      "customRequireTern": "req",
      "customRequireRootProject": "/home/user/project"
    }
```

**Comment by marijnh** [comment]
Not in a clean way. But you could try building a custom wrapper around the `node` plugin that hacks in something like this

**Comment by myshov** [comment]
@Redsandro unfortunately no...
