### ISSUE TITLE
How do I specify the module mapping in the node plugin?

### ISSUE THREAD

**Issue by bennidhamma** [marijnh/tern#547]
I am trying to generate a tree of transfer types from our server codebase into javascript. I've been hacking away at this for the last week or so and feel like I'm close.

I generate two files, a types.js javascript file which contains the javascript code which defines the constructors, properties, etc., and then I generate a separate JSON type def file.

We use browserfiy, so the node plugin works great as a base line, getting off the ground sort of thing for tern. When I reference the type tree in a file which does not require the actual javascript types, the JSON type def works great, but when I try and require the types.js dependency, all of my properties are clobbered and turned into '?'s.

I read that there should be a way to override the node parser via the modules property of the plugin, but I can't get this to work. The documentation says that the property should point to an object mapping module names to either a JSON object representing the defs inline, or a string specifying a file in the project directory to look for.

I've tried both of these, no dice. I'm not sure what I'm doing wrong. What is the module name correspond to? The variable the require stmt is assigned to? The variable name in the module.exports stmt? Something else?

thanks.

**Comment by bennidhamma** [comment]
I created a little test project that showcases the problem here:

https://github.com/bennidhamma/tern-test-node-plugin

hope that helps illuminate my situation a bit.

**Comment by angelozerr** [comment]
I think your JSON Type definition must use !node

See an exemple with tern express at
https://github.com/angelozerr/tern-node-express/blob/master/node-express.js#L79

2015-05-29 2:41 GMT+02:00 Ben Joldersma <notifications@github.com>:

**Comment by bennidhamma** [comment]
thanks @angelozerr. I've looked at your example, and grepped around in the tern repository - but I can't figure out what I'm supposed to put in there. 

What does the !node directive do?

**Comment by angelozerr** [comment]
The node tern plugin load module by using  :

 *  JSON Type Definition of the node.js like `fs` https://github.com/marijnh/tern/blob/master/plugin/node.js#L1648
 * custom JSON Type Definition which defines a `!node` https://github.com/marijnh/tern/blob/master/plugin/node.js#L132

**Comment by bennidhamma** [comment]
The tern documentation for the node plugin says:

"The plugin understands the following configuration parameters:"
...
"modules
Can be used to assign JSON type definitions to certain modules, so that those are loaded instead of the source code itself. If given, should be an object mapping module names to either JSON objects defining the types in the module, or a string referring to a file name (relative to the project directory) that contains the JSON data."

I'm assuming this means that I associate my desired JSON type definition to node module via a property named "modules" in the "node" object in the .tern-project file:

```
{
  "libs": [
    "browser",
    "jquery",
    "scout"
  ],
  "plugins": {
    "node": {
      "modules": {
        "ScoutData": "scout.json"
      }
    }
  }
}
```

Is that a correct interpretation of the documentation? Additionally, do I need to configure a '!node' directive in the JSON type definition? If so, I still don't understand what specifically I'm supposed to put in there.

Can you reproduce my problem in my test project, https://github.com/bennidhamma/tern-test-node-plugin ?

thank you

**Comment by bennidhamma** [comment]
A larger question is how can I effectively debug tern? I've tried putting some console.log statements in the source code, but when I run via vim, I don't see any of that output. Perhaps a different editor might have better support?

Is there any way to use chrome dev tools to step through the tern code via a debugger? That would be swell...

**Comment by bennidhamma** [comment]
Well. I got the debugger working and spent the last 4 hours or so trying to re-arrange the JSON in definition file to make this work.

I thought that the dontLoad directive might help put node in the back seat, and let the scout lib definition take over, but that just zeroed out the completions to null.

Running out of ideas.

**Comment by marijnh** [comment]
@angelozerr He clearly stated that he's using the `modules` option to the node plugin, so `!node` is not at all what he is trying to use.

@bennidhamma What I'm confused about in your demo is why the `ScoutData` json file (which I guess should define the the `$ScoutData` global) is missing? (Names in the `libs` section of your project config should refer to `.json` files)

**Comment by bennidhamma** [comment]
@marijnh I added the json and renamed the js files. the test project doesn't compile or anything, but I now have things working in my actual project directory, with the changes to tern in the https://github.com/marijnh/tern/pull/551 PR.
