### ISSUE TITLE
Add "object" as typespec

### ISSUE THREAD

**Issue by angelozerr** [marijnh/tern#554]
Today we have number, bool, string as primitive type, but when we wish to declara a !type to tell that a parameter of result fonction is an object, we must write with `?` : 

For instance JSON.parse returns an object, the JSON Type definition is : 
```json
"JSON": {
    "parse": {
      "!type": "fn(json: string) -> ?",
    }
}
```
I think it should be better to write : 

```json
"JSON": {
    "parse": {
      "!type": "fn(json: string) -> object",
    }
}
```

or

```json
"JSON": {
    "parse": {
      "!type": "fn(json: string) -> {}",
    }
}
```

So completion will provide method of objects for JSON.parse().

@marijnh what do you think about this idea?

**Comment by marijnh** [comment]
Tern has no concept of a generic object type. You can return `+Object`, if you want to, but I actually don't think this is helpful in many situations. Your example, `JSON.parse`, for one, can return anything. `JSON.parse("5")` gives a number, `JSON.parse("true")` a boolean, etc.

**Comment by angelozerr** [comment]
Ok thanks for your information. 

What do you think if we create a custom tern function which returns the well type of JSON.parse according the string parameter. If you are OK, I could try to create a PR for that.

**Comment by marijnh** [comment]
Why would anyone call `JSON.parse` on a static string?

**Comment by angelozerr** [comment]
Yes you are right, it seems that it's not very interesting, just for the demo.
