### ISSUE TITLE
`tern-before-change` hook causes jumping when used with `evil-mode` (Emacs)

### ISSUE THREAD

**Issue by emallson** [marijnh/tern#556]
**The Bug:** When I delete a segment of code with `dfx` (delete forward to the first x), the buffer scrolls to several very different positions in a very short period of time. Removing `tern-before-change` from the `before-change-functions` list causes this to stop.

**Reproducing:**

1. Install Emacs, Tern, Tern-Mode and Evil-Mode.
2. Begin editing a JS file. Write out a function, then go to the declaration line (`function foo(bar) { ... `) and run `df{`. The screen will jump upwards and then back down very rapidly (if the buffer cannot be scrolled then it does not occur).

Changing the "200 millisec" to  "600 millisec" in `tern-before-change` fixes it, but I am not sure what effect that would have on the actual behavior yet.

Also: it seems that `tern-before-change` is actually trying to wait until *after* the change to send the buffer, so why not use `after-change-functions`? I will experiment with this after work. Wanted to get it reported so I wouldn't forget.

**Comment by emallson** [comment]
I believe I have fixed this (without breaking anything) in https://github.com/emallson/tern/commit/6f62857086e7bb16a33f04e3d7a9a8ae544c5493, but I'm going to give it a few days of usage before submitting a PR because there don't seem to be any elisp tests.

**Comment by marijnh** [comment]
Has the patch stood the test? Should I merge it?

**Comment by emallson** [comment]
Not quite. Emacs idle-timer functions are not buffer-local as I'd initially thought. The result is that `tern-reparse-on-idle` gets run on other buffers. I need to fix that. Aside from that, it seems to work quite well.

**Comment by emallson** [comment]
A quick update on this: sorry that it took me so long. I was working with ES6/7 code for a while and couldn't really test my change on that. I've been back on ES5 code and the change I made has worked great. I'll submit a PR this evening once I'm off work.

**Comment by marijnh** [comment]
(Still hoping for that PR!)

**Comment by emallson** [comment]
@marijnh: sorry! just submitted PR

**Comment by marijnh** [comment]
Done via #593
