### ISSUE TITLE
"strong" for JSON Type definition 

### ISSUE THREAD

**Issue by angelozerr** [marijnh/tern#557]
The first time the `String#replace` signature method is OK:  pattern parameter has 2 types `string|RegExp` : 

![replace_ok](https://cloud.githubusercontent.com/assets/1932211/8007380/aaebb38c-0b9b-11e5-80eb-2c2f9f97be0a.png)

But if you fill pattern parameter with a number, pattern has 3 types `string|RegExp|number`:

![replace_nok](https://cloud.githubusercontent.com/assets/1932211/8007405/deeddc46-0b9b-11e5-82e0-35c97203417e.png)

It looks like the issue about JSDoc https://github.com/marijnh/tern/issues/536. To fix this issue, `strong` option gives the capability to set max weight when propagate is done.

I think for JSON Type Definition, it should use the same weight than JSDoc when propagate is done.

@marijnh what do you think about that?

**Comment by marijnh** [comment]
I think attached patch will fix this issue.

**Comment by angelozerr** [comment]
It works like a charm. Thanks!
