### ISSUE TITLE
ES2015 module support?

### ISSUE THREAD

**Issue by impinball** [marijnh/tern#559]
Obviously, #116 was little too broad, but with projects like Ember and Angular moving towards ES2015 module syntax, and the standard itself (hopefully) being officially published this month, I feel module support should be implemented relatively soon.

**Comment by sevin7676** [comment]
+1

**Comment by marijnh** [comment]
This is planned, but I am busy with other projects at the moment (which use ES6 modules, so this is also a pain point for me). I hope to have time to work on ES6 after the summer.

**Comment by impinball** [comment]
It's effectively a blocker for me for similar reasons.

**Comment by bananaoomarang** [comment]
Acorn already has support for module imports + a bunch of other stuff, right? What are the pain points/difficulties in getting tern to respect Acorn's ecma6+ parse formats? 

Not asking to say "why haven't you implemented this" (I'm sure it's not super simple or it would have happened!), just would like some pointers to see if I can get the ball rolling myself.

**Comment by LFDM** [comment]
This is really something that holds this project back for me a little too - maybe this could be done as a community effort...?

**Comment by impinball** [comment]
If someone can find time to open a PR, I'm pretty sure @marijnh would probably merge it.

**Comment by marijnh** [comment]
I've just pushed 2863d70 to master, which is the start of my own ES6 work. It causes Tern to parse its input as ES6 code, and to simply ignore node types it does not understand. This means that you now have an AST available with import/export statements, and could start doing intelligent things with those.

**Comment by gilligan** [comment]
@marijnh I would be very willing to donate on bounty source for this. I started working on a jsx/es6 project and we also use es6 modules - suddenly tern.js is useless and that is a huge productivity killer for me. 

I would not bother much about tern not being able to infer on some code but not getting any completions at all from react imports is awful.

what would be an appropriate donation for this ?

**Comment by marijnh** [comment]
For proper ES6 module support, which would include abstracting the concept of module resolution (so that node's rules are just one resolution strategy that can be replaced by another), I'd ask for 750 €.

**Comment by LFDM** [comment]
Well, that's a sum we should be able to raise - any volunteers? :)

**Comment by marijnh** [comment]
This has been implemented but is being held until some money is raised. See my comment at https://github.com/marijnh/tern/issues/116#issuecomment-131781238

**Comment by gilligan** [comment]
alright, donated $50 ;)

**Comment by gilligan** [comment]
@marijnh I tried the git repo you mentioned but using the vim plugin all I ever get back from tern is '' (empty string) ? Have there been any breaking changes to the protocol requiring changes in the editor plugins or what is going on ? I also tried it on plain es5 code and I also don't get any usable responses.

**Comment by marijnh** [comment]
@gilligan See my comment in #116

**Comment by marijnh** [comment]
Closed via #116
