### ISSUE TITLE
Can I define the key binding of Code Completions?

### ISSUE THREAD

**Issue by littlee** [marijnh/tern#562]
`Ctrl` + `Space` has conflict with my PC.

When I want to switch to another input method, I got to press `Ctrl` + `Space`

**Comment by marijnh** [comment]
There is nothing in Tern itself that even talks about key bindings. Which editor are you using?

**Comment by littlee** [comment]
Sublime Text 3,
the doc says that
>
Available actions
Code Completions. Press Ctrl+Space to show completions for current context. They can also appear automatically, depending on your ST preferences.
....

http://emmet.io/blog/sublime-tern/

**Comment by marijnh** [comment]
I am not involved in sublime-tern. Why don't you open an issue on https://github.com/emmetio/sublime-tern/ instead?
