### ISSUE TITLE
Release 0.11.1 ?

### ISSUE THREAD

**Issue by angelozerr** [marijnh/tern#564]
@marijnh I would like to know when you think you could create a release for tern 0.11.1?

I would like to create a release for https://github.com/angelozerr/tern-lint and https://github.com/angelozerr/tern-browser-extension, but I need https://github.com/marijnh/tern/issues/557 and https://github.com/marijnh/tern/pull/550

Thanks!

**Comment by marijnh** [comment]
I've just tagged 0.12.0 and pushed it to NPM.

**Comment by angelozerr** [comment]
Many thanks @marijnh !
