### ISSUE TITLE
[doc_comment] @return doesn't work if function doesn't returns something.

### ISSUE THREAD

**Issue by angelozerr** [marijnh/tern#566]
I use doc_comment with strong.

The following case works : 

```javascript
 /**
  * @return {Array.<String>}
  */
function f() {
  return null;
}

f()[0]. // [OK] : here Ctrl+Space shows String methods
```

but if you remove the return of the function, completion doens't work :

```javascript
 /**
  * @return {Array.<String>}
  */
function f() {
}

f()[0]. // [NOK] : none completion
```

**Comment by denis-sokolov** [comment]
Is that not expected behavior?
I assume strong inference from code takes precedence over incorrect comments.

**Comment by angelozerr** [comment]
> Is that not expected behavior?

"strong" for me, means that JSDoc annotations overides the JavaScript code, no?

**Comment by denis-sokolov** [comment]
In that case I suppose it's up to a personal preference.
For prototyping your interpretation is certainly more convenient.
For debugging the current behavior is more useful.
Of course, ideal scenario would be for type conflicts (in this case `undefined` vs `Array.String`) to be reported. This would make Tern a type checker, actually. (Unless the behavior is there, but I don't know about it yet. ^^)

**Comment by angelozerr** [comment]
> Of course, ideal scenario would be for type conflicts (in this case undefined vs Array.String) to be reported. This would make Tern a type checker, actually. (Unless the behavior is there, but I don't know about it yet. ^^)

I have started to support that inside tern-lint. See https://github.com/angelozerr/tern-lint/wiki/Validation-JSDoc and issues https://github.com/angelozerr/tern-lint/issues/30, https://github.com/angelozerr/tern-lint/issues/29

So I have created this issue to report an error with tern-lint in this case.
