### ISSUE TITLE
Tern creates too many type objects and runs out of memory

### ISSUE THREAD

**Issue by nightwing** [marijnh/tern#572]
Steps to reproduce: 

Add https://raw.githubusercontent.com/runefs/query-js/1a585d02859da/query.js as new file in
http://ternjs.net/doc/demo.html

Place cursor in the middle of `Tree` variable on first line and invoke autocompletion.
Do same for the `Query` variable on the first line, and `getSequqneceAndDefault` on the line 4

Browser freezes and crashes after using a gigabyte of memory

Tested on chrome 43

**Comment by marijnh** [comment]
Well, that took some time to debug, but patch a76763f3c9064 should address this.
