### ISSUE TITLE
Support multiple method signatures

### ISSUE THREAD

**Issue by vkalpias** [marijnh/tern#574]
Hi, 

We are integrating tern on our site in order to show autocomplete for our JavaScript API. In our API we have various methods that take different parameters. For example
```
setPosition(x, y, z)
```
or
```
setPosition(vector)
```

Is it possible to somehow allow definitions to accept methods with multiple signatures?

Thank you

**Comment by marijnh** [comment]
Nope, and this is not a planned feature at the moment. (It does come up regularly in JS code, but is hard to unify with Tern's function model.)

**Comment by AnasAl-tamemy** [comment]
I have the same issue, it would be great if you add this as a feature.

Thank you
