### ISSUE TITLE
Type of property changes after assignment of unknown type

### ISSUE THREAD

**Issue by vkalpias** [marijnh/tern#576]
I have a custom tern definition json which defines something like this;
```
{
    'Foo': {
        'prototype': {
             'prop': '+Bar',
             '!doc': 'Some docs here'
         }
    },
    'Bar': {
        ....
    }
}
```

So all good so far - when I write foo.prop I get proper docs for the 'prop' property. But if in my code I assign foo.prop to a variable whose type is unknown, I lose the docs for foo.prop from there on.

For example if I have this code:

```
var Test = function() {
    this.foo = new Foo();
}

Test.prototype.method = function (something) {
    this.foo.prop = something; // from now on this.foo.prop will not have docs
}
```

Is this a bug or is it intentional? Any way to fix it?

**Comment by marijnh** [comment]
I can not reproduce this. When I recreate the scenario you describe, the `prop` property is completed with and without that statement

**Comment by vkalpias** [comment]
So I have a <a href="https://playcanvas.com" target="_blank">playcanvas</a> script that looks like this:

```
pc.script.create('test', function (app) {
    // Creates a new Test instance
    var Test = function (entity) {
        this.entity = entity;
    };

    Test.prototype = {
        move: function (direction) {
            // tern loses type information for entity.rigidbody.linearVelocity from now on
            // if we uncomment this line then it's fine
            this.entity.rigidbody.linearVelocity = direction;
            
        }
    };

    return Test;
});
```

In this example there is a tern definition file that specifies the type of entity.rigidbody.linearVelocity. But I guess because we set it to 'direction' whose type is not known it loses the type information for linearVelocity after that.

**Comment by marijnh** [comment]
Well, that still doesn't give me enough to reproduce the issue. If you can give me a .js script, a .json file, and the precise call to `bin/convert` that shows the issue (write the variable you're interested in to a global so that it shows up in `convert`'s output), I can try to reproduce again.

**Comment by vkalpias** [comment]
So I think I managed to reproduce this like you said. Here is a js file: http://pastebin.com/7qMeD0uK  . Here is the definition file: http://pastebin.com/MUzBsPxE . 

This is what I see when running condense:
```
{
  "!name": "tern_bug.js",
  "e": {
    "!type": "+pc.Entity",
    "!span": "4[0:4]-5[0:5]"
  },
  "move": {
    "!type": "fn(direction: ?)",
    "!span": "30[2:4]-34[2:8]"
  }
}
```

This is wrong because I don't see a type for the variable named 'g'. If I uncomment the line in the js file I see this which is then correct:

```
{
  "!name": "tern_bug.js",
  "e": {
    "!type": "+pc.Entity",
    "!span": "4[0:4]-5[0:5]"
  },
  "move": {
    "!type": "fn(direction: ?)",
    "!span": "30[2:4]-34[2:8]"
  },
  "g": {
    "!type": "+pc.Vec3",
    "!span": "165[6:4]-166[6:5]"
  }
}
```

**Comment by marijnh** [comment]
I can reproduce this now, and the phenomenon is actually rather benign -- by assigning to the object's property, you're causing that object to get a property of that name, shadowing the prototype's property. I do think this is the right behavior in this situation.

**Comment by vkalpias** [comment]
Thanks for looking into this. Well not sure if it's the right behavior in general. It's certainly not the right behavior for our case.. We have a def file that specifies the type of each property. If they lose their type info whenever we assign stuff to them it means it will not autocorrect quite often. 

If it's not something that can be fixed thank you anyway :)

**Comment by angelozerr** [comment]
Its the same problem than multiple types parameters function from Def which was fixed and strong option for jsdoc

Perhaps It should be an option when Def Is loaded :set strong type like jsdoc  for property

**Comment by marijnh** [comment]
Attached patch makes the _guessing_ mechanism look at overridden properties when guessing the type of an empty property.  But note that such types won't propagate -- they'll only show up if you directly ask for the type (for example for completion) of the property itself, and don't 'flow' into the rest of the program.

**Comment by vkalpias** [comment]
That patch seems to do the trick :) 

Thanks a lot I really appreciate it!
