### ISSUE TITLE
Wrong "find definition" with sym-linked work folder

### ISSUE THREAD

**Issue by sigxcpu76** [marijnh/tern#577]
I've raised an issue with atom-ternjs here: https://github.com/tststs/atom-ternjs/issues/97 . I don't know if the issue comes from it or the tern server, so I've put it here, too.

I've just installed Atom 1.0 and atom-ternjs and "Find definition" points to a wrong path.

Here's an example:

I have a ```./lib/commons/redis-serializer.js``` module with the absolute path ```/Users/sigxcpu/work/tcn/node/agent-backend/lib/commons/redis-serializer.js```.
"Find definition" opens ```/Users/sync/work/tcn/node/agent-backend/lib/commons/redis-serializer.js```.

Notice the user part of the path disappeared.

The ```require``` looks like this: ```let serializer = require('../lib/commons/redis-serializer');```

The issue is that ```/Users/sigxcpu/work``` is a symlink to ```/Users/sigxcpu/sync/work```.
If the project is opened from the real folder, everything is fine, but opening it from the symlinked folder has this problem.

I've attached the "good" and the "bad" paths. It looks like the sym-linked version is absolute compared to relative in non sym-linked one.

![good-path](https://cloud.githubusercontent.com/assets/737085/8487103/5fb9ad7e-2112-11e5-9f81-99229e22ce11.png)
![bad-path](https://cloud.githubusercontent.com/assets/737085/8487107/64dc9c9e-2112-11e5-8f58-e04053e2a0b2.png)

**Comment by marijnh** [comment]
I think you'll have to look into the Atom plugin here. Tern doesn't do symlink resolution itself, but depends on the wrapper code (so the standard server will use Node's code, which doesn't appear to have this issue). Closing, but feel free to reopen if you have more evidence pointing at my code.
