### ISSUE TITLE
Sublime Text 3

### ISSUE THREAD

**Issue by anxoocampo** [marijnh/tern#580]
Hi,

I've just installed this package and I can't open Sublime Text 3 anymore... I'll be force to uninstall this package.

Regards.

**Comment by marijnh** [comment]
Since you didn't bother to provide any error messages or details, and this is not a problem that is occurring for everyone, I'm sorry, but there's really not enough info for me to debug this.

**Comment by anxoocampo** [comment]
Hi @marijnh,
Unfortunately, I couldn't provide any further error message as I couldn't even open ST3 after the installation of this package... 
It just gets frozen, I've tried it few times with the same result every time, it just looks it runs out of memory or similar. I'm currently working with an Angular JS project in a Mac with 8GB of RAM memory.
Not sure what further details you would like me to provide...
Regards.

**Comment by marijnh** [comment]
I looked at the ST docs and couldn't find any way to make it spit its internal console output to stdout, so I guess that, indeed, if the app hangs without error messages and without allowing you to open the ctrl-~ console, there's no clear way to get diagnostic information out of it.

You could see if there's a Tern (node) process active during the hang, and you could try running the server manually (by starting the Tern binary in your project directory, with the `--verbose` flag) before starting ST, to see if any requests are being made to it.
