### ISSUE TITLE
Make parser pluggable?

### ISSUE THREAD

**Issue by louy2** [marijnh/tern#585]
Given parsers all parse to ESTree, is it possible to change the parser Tern uses? How integrated is Tern with Acorn?

The question comes to my mind when I saw Esprima is consistently faster than Acorn according to the benchmark: http://marijnhaverbeke.nl/acorn/test/bench.html

**Comment by marijnh** [comment]
No, it is not. Only Tern has an error-tolerant parser, and you definitely need that to be able to parse half-edited code.
