### ISSUE TITLE
Promise fulfill value is incorrect when defined in def

### ISSUE THREAD

**Issue by othree** [marijnh/tern#587]
Found two strange bahavior.
I have a [plugin][1] defines fetch method.
And use `.tern-project`:

    {
      "libs": [
        "ecma6",
        "fetch"
      ]
    }

And write the following code:

    var x = fetch('');
    x.then(function (res) {
      res._ 
    });

When cursor at line 3, after the `res.` ( `_` is cursor position).
I expect to see properties of Response.
But I saw lot of properties.

The reason is the type should be `Response`.
But it actually becomes `Response|Blob|string....` (`:TernType` could saw part of the type)
And I found its cause by some properties(method) return another promise fulfilled by other data type.
ex: [blob]

So I have to remove these type define.
Also remove the entire `Request` part.
The result new def file is on [gist][2].

With this def file.
The type of `res` is correct.
And the properties tern provided is what I expect.

Another strange behavior is the `Reqeust` part.
If I keep this part in def file.
The behavior will not change.
I have to delete it.
Or remove the `!type` line of each properties return another promise.
Just like what I do to `Response` part.

[1]:https://github.com/othree/tern-fetch/blob/master/fetch.json
[blob]:https://developer.mozilla.org/en-US/docs/Web/API/Body/blob
[2]:https://gist.github.com/othree/1d5f235b7ed0ae89742f

**Comment by marijnh** [comment]
It seems all the different Promise types created by the definition file end up sharing a single instance, which results in the kind of issue you saw. Attached patch fixes this. Please let me know if it solves your issue.

**Comment by othree** [comment]
Confirm Fixed, thank ~
