### ISSUE TITLE
Autocomplete is Empty for Class Properties 

### ISSUE THREAD

**Issue by mtangoo** [marijnh/tern#588]
I have this test code
```js
var Person = Class.extend({
  init: function(isDancing){
    this.dancing = isDancing;
  },
  dance: function(){
    return this.dancing;
  }
});
 
var Ninja = Person.extend({
  init: function(){
    this._super( false );
  },
  dance: function(){
    // Call the inherited version of dance()
    return this._super();
  },
  swingSword: function(){
    return true;
  }
});
 
```
Now when I create Persone like `var pp = new Person(false);`  it works, bringing Person as guess type (i think it can be improved to take arguments from init function, but it at least works). But when I type `pp.` then I expect init, and dance functions as autocomplete items. It instead brings empty array.

I think TernJs does not deal with these kind of code yet: Am I correct on that?
Thanks for great tool!

**Comment by angelozerr** [comment]
Class is not a JavaScript keyword. I suppose you try http://ejohn.org/blog/simple-javascript-inheritance/

So you must write a tern plgin which support Class features.

**Comment by mtangoo** [comment]
Ok, thanks. I'm not JS Maverick, so I thought its somehow intrinsic JS
