### ISSUE TITLE
Is tern supposed to be able to jump between different files

### ISSUE THREAD

**Issue by IvanMalison** [marijnh/tern#597]
I've never managed to get tern to teleport to definitions located in other files, even when I use the requirejs and node plugins. Is this a limitation of tern or have I just failed to configure it properly?

Feel free to close this issue...

**Comment by marijnh** [comment]
Going by your account picture, I'm assuming you're using Emacs? If so, yes, Tern can, when it knows that the files belong to the same project (same directory or a `.tern-project` file above both of them), and it can figure out what an identifier refers to (using the global scope or a module-loader plugin), jump across files. It works, for example, if you open the tern sources itself, which come with a `.tern-project` file that loads the node module system.

**Comment by IvanMalison** [comment]
So I had actually just tried that before I made this issue and thought that I had verified that things didn't work. Now I see that they do actually work, with an important caveat. Take the following example from test/fragments.js

line 7 is 
``` javascript
var server = new tern.Server({defs: [util.ecma5]});
```

If you jump to definition on Server things work as i would expect, but if you jump to definition on the tern variable itself, it just takes you to the location where the variable itself is defined.

Unfortunately I work in a codebase where people do a lot of

module.exports = TheOnlyClassInTheFile

so my jump to definitions almost never work. Is there any way to make the default behavior of the emacs plugin to be to go to the source defintion?

**Comment by marijnh** [comment]
Usually, when you jump to a variable's definition, you are interested in the actual point where the variable is defined. We could create a separate command 'jump to type', which jumps to the place where the type in the variable is defined, but I'm not sure whether that distinction is easy for users to grasp.

**Comment by IvanMalison** [comment]
> Usually, when you jump to a variable's definition, you are interested in the actual point where the variable is defined. We could create a separate command 'jump to type', which jumps to the place where the type in the variable is defined, but I'm not sure whether that distinction is easy for users to grasp.

That seems like a good idea to me. Your users are programmers, they can probably figure it out, right?

**Comment by marijnh** [comment]
I've changed the behavior of jumping to imports -- from _uses_ of the import, you still jump to the import/require itself. If you then press alt-. _again_, on the import itself, it'll take you to the actual source of the module.

**Comment by IvanMalison** [comment]
great! that seems like pretty reasonable/intuitive behavior. Thanks for doing this

**Comment by anthonypt87** [comment]
Thanks for implementing this! Is there the equivalent for vim? I'm also having trouble jumping across files using https://github.com/marijnh/tern_for_vim

**Comment by marijnh** [comment]
Tern_for_vim is also able to jump between files. Make sure you have your project configuration (especially the parts relating to module system) set up correctly.

**Comment by base698** [comment]
Can you link to an example project showing how to correctly set it up?

**Comment by marijnh** [comment]
Which module system are you using? If you're going through an import, you need to jump twice -- once to get to the import/require, and then once more to get to the actual source. Also, this only works in the latest release.

This works for me:

.tern-project:

```
{
  "plugins": {
    "node": {},
    "es_modules": {}
  }
}
```

a.js:

```
export function foo() {}
```

b.js:

```
import {foo} from "./a"
```

If I move my cursor onto `foo` in `b.js`, jump-to-definition gets me to `a.js`.

**Comment by base698** [comment]
I'm in a node project that uses in b.js:

var foo = require('a.js').foo;



On Wed, Jan 27, 2016 at 12:48 AM, Marijn Haverbeke <notifications@github.com

**Comment by marijnh** [comment]
I don't think node will resolve to a  local file if you do `require('a.js')`. The correct way is `require("./a")`. As such, Tern's node plugin won't resolve that either.

**Comment by base698** [comment]
Sorry yes it's require('./a.js') I haven't had coffee yet :)

Actually a lot of our files use require(__dirname + '/a.js') or
require(process.cwd() + '/a.js').  Maybe that's the issue?

**Comment by marijnh** [comment]
Tern can't see through computed requires, so that might indeed be the issue. Doing `require(__dirname + "/a")` appears to be completely equivalent to `require("./a")`, and thus probably not a very useful thing.

**Comment by base698** [comment]
That's what it was!  Thanks so much for your help, doing a refactor anyway
so making tern work with our code base is a god send.  Definitely donating
now :)

**Comment by IvanMalison** [comment]
@marijnh the second part of this is still not working for me. Can you point to the code that should be handling this so I can try to debug what is going on?

**Comment by luc1ph3r** [comment]
Imagine this project tree:
```shell
.
└── src
    ├── a
    │   └── a_file.js
    └── b
        └── b_file.js
```

Now, imagine files as:
```javascript
// a_file.js
export default class TestClass { ... }
```

```javascript
// b_file.js
import TestClass from '../a/a_file';
```

In this case, everything works as expected and tern is able to go to definition of TestClass. But then let's use babel plugin that can search for files relatively to project's root folder. Then our `b_file.js` will look like this:
```javascript
// b_file.js
import TestClass from 'a/a_file';
```

Now tern says that he wasn't able to find the definition of TestClass.
Will tern be able to resolve this kind of module importing or is it already (maybe I do something wrong)?

I'm using the latest version of [tern_for_vim](https://github.com/ternjs/tern_for_vim) and I also have a `.tern_project` config in my project folder.

**Comment by marijnh** [comment]
> In this case, everything works as expected and tern is able to go to definition of TestClass. But then let's use babel plugin that can search for files relatively to project's root folder.

If you're using odd resolution strategies, you'd have to write a custom resolver plugin to support them (see the node_resolve plugin as example). None of the plugins in the distribution support this.

**Comment by luc1ph3r** [comment]
> If you're using odd resolution strategies, you'd have to write a custom resolver plugin to support them

I see, it makes sense. Thanks for quick response!
