### ISSUE TITLE
Closure not recognizing constructors/methods on namespaced globals

### ISSUE THREAD

**Issue by mtaran-google** [marijnh/tern#599]
(repro-able in http://codemirror.net/demo/tern.html)
If I try to autocomplete at the `|` in 
```js
var Bar = function() {};
Bar.prototype.a = function() {
  this.|
};
Bar.prototype.b = function() {};
```
I get `a` and `b` as options, as expected. But when I try it in

```js
foo.Bar = function() {};
foo.Bar.prototype.a = function() {
  this.|
};
foo.Bar.prototype.b = function() {};
```
I get nothing, because tern doesn't recognize `foo.bar` to be the constructor. This makes Tern not really work for files written to work with the Closure library's/compiler's standard namespacing system, as in https://github.com/google/closure-library/blob/master/closure/goog/array/array.js.

The example would work if I had a `var foo = {}` line above, but that normally happens as part of a call above like `goog.provide('foo.Bar')` (cf https://github.com/google/closure-library/blob/master/closure/goog/base.js#L268). Since that happens via a lot of indirection, tern unsurprisingly can't pick it up even when the whole base.js is pasted into the file...

**Comment by marijnh** [comment]
Tern needs to have an object type for (in your case) `foo` to even be able to represent the path `foo.Bar`. Have you tried using the plugin at https://github.com/google/tern-closure ? That supposedly implements `goog.provide` and might solve your issue.

**Comment by mtaran-google** [comment]
I'm aware of that plugin and we're working on getting it up and running in a web browser (since it was built to run on node.js). But that's still a ways out, so I was hoping you'd be able to suggest some interim solution, such as some way that I'd be able to tell tern to (say) treat all `?` objects as `{}` or something like that.

**Comment by marijnh** [comment]
This problem has come up before and in other contexts, and after some thinking, I think I found a rather elegant solution. Attached patch should help with this.
