### ISSUE TITLE
[tern-es6] completion after "import {" throws error

### ISSUE THREAD

**Issue by angelozerr** [marijnh/tern#606]
I have tried the demo http://ternjs.net/es6/doc/demo/#ES6

Write in the editor `import {` and open completion, you have the error `Uncaught TypeError: Cannot read property 'type' of null`

**Comment by marijnh** [comment]
That was a bug in Acorn's loose parser. Attached patch should fix it (I'll tag a new Acorn version when I release the ES6 stuff)
