### ISSUE TITLE
[tern-es6] completion for imported from

### ISSUE THREAD

**Issue by angelozerr** [marijnh/tern#608]
With the demo http://ternjs.net/es6/doc/demo/#ES6, it should be cool if we could have completion for imported from: 

```javascript
import {list} from "// here Ctrl+Space shows /list "
```

@marijnh if you have no time to do that, I will try to study to implement that once tern-es6 will be available in this git repository.

**Comment by marijnh** [comment]
This already works on the node-based server, which has access to the filesystem. On the online demo, you have to type `"./` first, since relative paths are all it can resolve.

**Comment by angelozerr** [comment]
Thanks @marijnh for your info.
