### ISSUE TITLE
[tern-es6] jump to definition for imported from

### ISSUE THREAD

**Issue by angelozerr** [marijnh/tern#609]
With the demo http://ternjs.net/es6/doc/demo/#ES6, it should be cool if we could have jump to definition for imported from:

```javascript
import {list} from "list // here jump to definition open list tab "
```

@marijnh if you have no time to do that, I will try to study to implement that once tern-es6 will be available in this git repository.

**Comment by marijnh** [comment]
This was implemented already, but had a bug. Fixed now.

**Comment by angelozerr** [comment]
Works like a charm now, thanks!
