### ISSUE TITLE
Completion doesn't work with referenced Object literal again

### ISSUE THREAD

**Issue by angelozerr** [marijnh/tern#610]
The issue https://github.com/marijnh/tern/issues/508 doesn't work with the demo http://ternjs.net/doc/demo.html

It seems that it's a problem with `acorn walk` which is called by `exports.parentNode` (of infer.js)

With old version of acorn we had :
 
```javascript
base.VariableDeclaration = function (node, st, c) {
  for (var i = 0; i < node.declarations.length; ++i) {
    var decl = node.declarations[i];
    if (decl.init) c(decl.init, st, "Expression");
  }
};
```

and now we have : 

```javascript
base.VariableDeclaration = function (node, st, c) {
  for (var i = 0; i < node.declarations.length; ++i) {
    c(node.declarations[i], st);
  }
};
```

**Comment by marijnh** [comment]
Works again in current master branch.

**Comment by angelozerr** [comment]
you mean current branch of acorn or tern? I have just tested with the online demo http://ternjs.net/doc/demo/#requirejs but it doesn't work (but I think demo was not updated).

**Comment by marijnh** [comment]
If I type `requirejs.config({` there an complete, I get the appropriate properties that the `config` function expects.

**Comment by angelozerr** [comment]
Yes this case works, the case which doesn't work is :

```javascript
var c = { // here completion doesn't work.
require.config(c)
```

**Comment by marijnh** [comment]
Okay, I see what you mean now. See attached patch.

**Comment by angelozerr** [comment]
Many thanks, it works like a charm!

**Comment by angelozerr** [comment]
Perhaps we shoudl add a test for this case.

**Comment by marijnh** [comment]
Sounds like a good idea. Just append it to the other tests for the literal property completion feature.
