### ISSUE TITLE
When destructuring, returned values cannot be ignored

### ISSUE THREAD

**Issue by MarcelGerber** [marijnh/tern#617]
1. Go to http://ternjs.net/doc/demo/#simple
2. Paste the line below
3. Press `Ctrl+Space` to request autocompletion
4. Have a look at the console

``` es6
let [a, , b] = [1, 2, 3];
```

Result:
```
Uncaught TypeError: Cannot read property 'type' of null
connectPattern @ infer.js:1251
inferPatternVisitor.ArrayPattern @ infer.js:1243
[...]
```

Per https://developer.mozilla.org/de/docs/Web/JavaScript/Reference/Operators/Destructuring_assignment#Ignoring_some_returned_values, "ignoring returned values" is explicitly allowed.

**Comment by marijnh** [comment]
Indeed. Forgot about holes in arrays again. Attached patch fixes this.
