### ISSUE TITLE
ecmaScript config can be strange

### ISSUE THREAD

**Issue by angelozerr** [marijnh/tern#619]
In tern file there is a new property confg.ecmaScript. In my case I don't use it and I set the well ecma version.

For instance I write this .tern-project : 

```json
{
  libs:["ecma5"]
}
```

But because of config.ecmaScript is set to true, ecma6 is added.

It should be cool if we could customize ecma, with libs : 

 * if libs:["ecma5"] =>  config.ecmaVersion = 5
 * if libs:["ecma5", "ecma6"] =>  config.ecmaVersion = 6

**Comment by marijnh** [comment]
We're defaulting to ES6 now (since it is backwards-compatible) and you have to explicitly set it to 5 to opt out. Including `"ecmaScript: 5"` is exactly as much work as explicitly loading the `"ecma5"` def (which would already be loaded by default), so I do not think this is a useful idea.

**Comment by angelozerr** [comment]
tern.java provides an UI to select tern plugins, and it's generic :

![](https://github.com/angelozerr/tern.java/wiki/images/EclipseIDE_ECMAScriptCheckModule.png)

It adds in the libs field the selected plugins. So if I understand your comment, I must change my code for ecma and update the ecmaScript and not the libs.

**Comment by marijnh** [comment]
Don't let the user choose the `ecma*` defs, just let them specify an ecmascript version and let the server's default behavior do the rest.

**Comment by angelozerr** [comment]
Ok thanks for your suggestion!

**Comment by angelozerr** [comment]
@marijnh IMHO I think there are more people which develop ES5 (and without ES6 modules). I think default config should be : 

```javascript
var defaultConfig = {
...
  ecmaScript: false,
  ecmaVersion: 5,
...
}
```

I'm afraid that tern users (like me) are lost with "es_modules" which doesn't use topScope (global scope).

**Comment by marijnh** [comment]
That's a very good point, I actually didn't think the implications of enabling `es_modules` by default though. I've pushed a patch that fixes that (you have to explicitly enable ES6 modules if you want them).
