### ISSUE TITLE
[node] Completion for all required modules doesn't work (regression)

### ISSUE THREAD

**Issue by angelozerr** [marijnh/tern#620]
Before tern-es6 we could benefit with completion for the all node required module. Now we cannot: 

```javascript
require(" // (NOK) here Ctrl+Space should show the full list of node modules but id doesn't work.
```
Today, only completion works if we type one character : 

```javascript
require("f // (OK) here Ctrl+Space shows fs, it works. 
```

**Comment by marijnh** [comment]
Patch 5f774fb addresses this

**Comment by angelozerr** [comment]
Thanks @marijnh! It works great for modules defined inside tern node plugin, but not for custom file. You need to type `./` and do Ctrl+Space to show modules. Perhaps you want this behaviour, but before tern-es6, you will see the whole modules (fs, etc and custom modules)

**Comment by marijnh** [comment]
>  Perhaps you want this behaviour,

Yes, this is what I intended. I feel the completions will get very messy otherwise, and typing `./` to suggest you want a local completion isn't a big effort.

**Comment by angelozerr** [comment]
> and typing ./ to suggest you want a local completion isn't a big effort.

I agree, I would like just know if it was the behaviour that you wished. I will explain that in the tern.java wiki.
