### ISSUE TITLE
please re-open ES6 features bounty

### ISSUE THREAD

**Issue by paulvi** [marijnh/tern#623]
please re-open ES6 features bounty at https://www.bountysource.com/issues/1141202-support-es6-features

ref #116, https://github.com/Nodeclipse/www.nodeclipse.org/commit/f72901e3ed2c9d4b93673c79823fa04c41436029

**Comment by marijnh** [comment]
The code has already been merged. What would be the point of reopening?

**Comment by paulvi** [comment]
Well, I thought it was the only way to thank. But now there is https://marijnhaverbeke.nl/fund/

What would be after surpassing 5000 per month goal? Giving away or hiring people?

I am so sorry touching the sensitive side of open source, I just fear of some "Marijn Inc" coming.
Personally I don't see other way myself. I wish you success and mind peace, just be true to yourself and others, stay what your values are in advance.

**Comment by marijnh** [comment]
If the work volume of my OSS work becomes too much for me to handle alone, and the funding allows it, yes, I will probably collaborate with other people. I do not see why that would be anything to fear.
