### ISSUE TITLE
[ES6] crash server when completion is used with import which is not valid

### ISSUE THREAD

**Issue by angelozerr** [marijnh/tern#628]
When import is used, the ssntax must be correct otherwise tern server crashes.

 * first pattern : import {List} from "./list"

```javascript
import // here Ctrl+Space throws the error : walk.js:36 Uncaught TypeError: Cannot read property 'type' of null
```

```javascript
import {// here Ctrl+Space throws the error : walk.js:36 Uncaught TypeError: Cannot read property 'type' of null
```

```javascript
import {} from  // here Ctrl+Space doesn't throw error
```

 * second pattern : import * as myMath from "./mymath"

Same problem if * as myMath  doesn't exist.

**Comment by marijnh** [comment]
How about an example of an import that causes a crash?

**Comment by angelozerr** [comment]
@marijnh sorry for my mistake, I have updated the issue.

**Comment by marijnh** [comment]
This has been fixed in Acorn already. I forgot to update the module on the server, which I've done now.

**Comment by angelozerr** [comment]
Ok thanks for your info.
