### ISSUE TITLE
Unsafe implementation of function signal() in signal.js

### ISSUE THREAD

**Issue by dmitriiKovchin** [marijnh/tern#634]
Current implementation assumes that 'arr' can't be changed  while we going through array, but if 'arr[i].call(this, a1, a2, a3, a4)'  lead calling of 'off(type, f)' we miss handlers. Probably we should protect  'arr'  from modification, copying it or prevent modification throwing exception if we tries to update this array while we going through elements.

**Comment by marijnh** [comment]
Good point. Attached patch should help.
