### ISSUE TITLE
Emacs tern-find-definition fails for React component

### ISSUE THREAD

**Issue by benzitohhh** [marijnh/tern#636]
Given a project with these two files...
```javascript
// MyComponent.js
var React = require('react');
var MyComponent = React.createClass({ ... });
module.exports = MyComponent;

// main.js:
var MyComponent = require('./MyComponent');
```

*Action:*
In emacs, position the point after the closing paren in `main.js`, and type`M-.`

*Expected behaviour:*
Tern should jump to `MyComponent.js`.

*Actual behviour:*
But tern jumps to the react sourcecode (`ReactClass.js`).

*Server debug:*
The server debug looks like this:
```javascript
Request: {
  "query": {
    "end": 42,
    "file": "main.js",
    "type": "definition",
    "variable": null
  }
}
Response: {
  "doc": "Legacy hook",
  "origin": "MyComponent.js",
  "start": 25936,
  "end": 27597,
  "file": "node_modules/react/lib/ReactClass.js",
  "contextOffset": 50,
  "context": "eateClass: function(spec) {\n    var Constructor = "
}
```

*IMPORTANT*
to replicate this problem, the `react` module must be installed (i.e. do `npm install`). Without it, the problem does not happen.

*Example project:*
Please see this github repo for a simple example project: https://github.com/benzitohhh/tern-react-problem

**Comment by marijnh** [comment]
In this case, it'll jump to the definition of the type, and it can't know that this variable definition is where you would consider the type to be defined. There are analogous situations where storing a type in a variable should *not* make that variable the source location of the type. So I can't think of a way to make Tern behave the way you are asking for, here.

**Comment by benzitohhh** [comment]
ok no worries @marijnh, thanks for checking.
