### ISSUE TITLE
condense ignores @type-annotated properties with value null or undefined

### ISSUE THREAD

**Issue by demonfiddler** [marijnh/tern#637]
Firstly, congratulations on an impressive product.

I have a large (2.5MB) JavaScript library, generated from XSDs, for which I wish to provide tern support (in Tern Eclipse IDE, not that it's relevant). The JavaScript is JSDoc3-annotated with (@)constructor, extends, memberOf, type, name as appropriate.

The condense tool emits JSON descriptors for all the _types_ in my library but although these descriptors have metadata for _methods_ defined by the prototype, they lack metadata for _properties_ defined by the prototype; the constructors do not define any properties. So the resulting content assist, doc hovers, validation etc. is incomplete and inaccurate. By contrast, Tern's built-in descriptors (defs/browser.json, for example) have "prototype" properties that describe the members but, from what I can see, appear to be properties that were actually defined in the constructor rather than the prototype.

UPDATE(1): I have subsequently discovered the reason why these properties are being ignored. If the property is unassigned, or is assigned the value null or undefined, the property does not get included in the condense output. From what I can tell, initializing the property to any value other than null or undefined is sufficient to ensure its inclusion in the output.

UPDATE(2): Having spent an entire day stepping through the tern code in the debugger, I finally determined that the parseTypeOuter() function in doc_comment.js expects the type name to be enclosed in {} characters. Do this and everything works as expected. Unfortunately my generated JavaScript was not doing not do this because Eclipse JSDT content assist expects @type name without the {} characters! So much for standards...

**Comment by demonfiddler** [comment]
Closing as Not A Bug.

**Comment by marijnh** [comment]
So the rationale for this behavior is that things without value are probably not interesting. If it would be useful to you, I could add an option to disable it (I think we just have to add a few lines of code to the `if (!actual)` clause in the `reach` function) and expose that through the `condense` binary.

**Comment by demonfiddler** [comment]
@marijnh thanks for the response, the rationale is reasonable in the general case. In our own particular use case we do have type information for all properties, and provided the types are enclosed between {} characters all works as desired. I could imagine that there might be circumstances where you're interested in the doc even if no type info is available.

As an aside - it would be good if the doc_comment 'strong' option be exposed as a condense binary argument. I want my content assist and JSDoc hovers to reflect the type as documented rather than the type as might subsequently be assigned - especially in client code, which might be wrong!

**Comment by marijnh** [comment]
You should be able to pass `--plugin 'doc_comments={"strong": true}'` to `condense`.

**Comment by demonfiddler** [comment]
Doh, of course! Thanks  :-)
