### ISSUE TITLE
ES6 Promise error

### ISSUE THREAD

**Issue by sigxcpu76** [marijnh/tern#646]
It happens when the cursor is over the ```function``` keyword in ```...then(function(...```

TypeError: self.hasProp is not a function at /Users/sigxcpu/.atom/packages/atom-ternjs/node_modules/tern/lib/def.js:633:37 at fn.computeRet (/Users/sigxcpu/.atom/packages/atom-ternjs/node_modules/tern/lib/def.js:257:26) at fn.computeRet (/Users/sigxcpu/.atom/packages/atom-ternjs/node_modules/tern/lib/def.js:257:26) at fn.computeRet (/Users/sigxcpu/.atom/packages/atom-ternjs/node_modules/tern/lib/def.js:257:26) at computeReturnType (/Users/sigxcpu/.atom/packages/atom-ternjs/node_modules/tern/lib/infer.js:1826:19) at typeFinder.CallExpression (/Users/sigxcpu/.atom/packages/atom-ternjs/node_modules/tern/lib/infer.js:1883:14) at findType (/Users/sigxcpu/.atom/packages/atom-ternjs/node_modules/tern/lib/infer.js:1917:21) at typeFinder.MemberExpression (/Users/sigxcpu/.atom/packages/atom-ternjs/node_modules/tern/lib/infer.js:1886:41) at findType (/Users/sigxcpu/.atom/packages/atom-ternjs/node_modules/tern/lib/infer.js:1917:21) at computeReturnType (/Users/sigxcpu/.atom/packages/atom-ternjs/node_modules/tern/lib/infer.js:1817:14)

I don't know what else to provide to help. The tern server is started and used by atom-ternjs plugin for Atom editor.

**Comment by sigxcpu76** [comment]
I have more information. It always happens starting with the second ```.then``` in chain. First one is OK.

**Comment by marijnh** [comment]
It would help if you provided a self-contained code example that triggers the problem. This code, which does have a chain of two `then` calls, doesn't appear to trigger it:

```javascript
Promise.resolve(44)
  .then(function(x) { return x + 1 })
  .then(function(x) { return String(x) },
        function(err) { console.log(err) })
```

**Comment by sigxcpu76** [comment]
I've reinstalled atom-ternjs package and it looks like your recent patch (for #651 ) is in there already, like the dependencies are git based (although they don't look like it).

Anyway, with the current reinstall, this issue (#646) is not reproductible anymore (although I did reproduce it today every time doing a clean install of atom-ternjs and therefore tern itself).

If you wish you can close it for now and I'll comment again if it happens.

Thank you.

**Comment by sigxcpu76** [comment]
Found it!

This exact code triggers the error:

```
'use strict';

const amqplib = require('amqplib');
const bunyan = require('bunyan');

let amqpConnection, amqpChannel, amqpURL;

function init(url) {
  amqpURL = url;
  return amqplib.connect(url)
    .then(function(conn) {
      amqpConnection = conn;
      amqpConnection.on('error', reconnect);
      return amqpConnection.createChannel();
    })
    .then(function(channel) {
      amqpChannel = channel;
      channel.on('error', reconnect);
      return channel.assertQueue('', {
        autodelete: true,
        exclusive: true
      });
    });
}

```

When the cursor is over ```function``` in 2nd ```then``` it throws:
```
TypeError: self.hasProp is not a function at /Users/sigxcpu/.atom/packages/atom-ternjs/node_modules/tern/lib/def.js:633:37 at fn.computeRet (/Users/sigxcpu/.atom/packages/atom-ternjs/node_modules/tern/lib/def.js:257:26)
        at fn.computeRet (/Users/sigxcpu/.atom/packages/atom-ternjs/node_modules/tern/lib/def.js:257:26)
        at fn.computeRet (/Users/sigxcpu/.atom/packages/atom-ternjs/node_modules/tern/lib/def.js:257:26)
        at computeReturnType (/Users/sigxcpu/.atom/packages/atom-ternjs/node_modules/tern/lib/infer.js:1826:19)
        at typeFinder.CallExpression (/Users/sigxcpu/.atom/packages/atom-ternjs/node_modules/tern/lib/infer.js:1883:14)
        at findType (/Users/sigxcpu/.atom/packages/atom-ternjs/node_modules/tern/lib/infer.js:1917:21)
        at typeFinder.MemberExpression (/Users/sigxcpu/.atom/packages/atom-ternjs/node_modules/tern/lib/infer.js:1886:41)
        at findType (/Users/sigxcpu/.atom/packages/atom-ternjs/node_modules/tern/lib/infer.js:1917:21)
        at Object.exports.expressionType (/Users/sigxcpu/.atom/packages/atom-ternjs/node_modules/tern/lib/infer.js:1972:12)
```

**Comment by marijnh** [comment]
Thanks. That allowed me to find the problem.
