### ISSUE TITLE
[Feature Request] Expose new "reset" request type to the JSON API

### ISSUE THREAD

**Issue by eranif** [marijnh/tern#647]
Hi,

It will be great if a new `query` type `reset` is added to the JSON API.
The expected behavior is to clear the cached files and start from scratch.

I'd rather sending a `reset` command to `tern` rather than restarting it (on Windows, the restart of a process is a slow operation... )

Thanks

**Comment by marijnh** [comment]
You mean including forgetting which files are loaded? Or just clear the currently loaded type graph?

**Comment by eranif** [comment]
Clear the currently loaded type graph ( I am not sure what it is, I am assuming its something similar to AST). 
It should have the equivalent effect of stopping and starting (aka "restarting") tern from the command line.

**Comment by marijnh** [comment]
Implemented in attached patch. Fully restarting the server will also cause its list of loaded files to be cleared (i.e. files that you've uploaded will be forgotten), which might not be what you want here. I've added a boolean flag in the query object to toggle this (http://ternjs.net/doc/manual.html#req_reset)

**Comment by eranif** [comment]
Thanks for the new API.
However, it seems to have no effect...

(I confirmed that I am using the latest tern JS source code)

Here is an example, consider the following 2 files project:

`main.js` with the following content:

```
var m = require("./module.js");
m.fooBar();
m.baz();
```

and `module.js` with the following content:

```
module.exports = { 
    fooBar : function() {},
    baz : function() {}
}
```

typing `m.` in the `main.js` file gives the proper completion entries - so far so good.

At some point, I have extended `module.js` with another function so now it looks like this:
```
module.exports = { 
    fooBar : function() {},
    baz : function() {},
    bazKirk : function() {}
}
```

Once the user hit `Ctrl-S` (save file) CodeLite triggers a `reset` request (I have no indication if it worked or did anything, since the output is empty)

At this point, if I type `m.` in `main.js` I get the following completion box from CodeLite:
![bad-cc](https://cloud.githubusercontent.com/assets/3677711/10131520/952b1a22-65d9-11e5-95f2-499a709f7942.png)

Checking out what did `tern` replied I see that CodeLite is simply showing what it was asked to display:

CodeLite request:
```
POST / HTTP/1.1
From: Eran Ifrah
User-Agent: CodeLite IDE
Content-Type: application/x-www-form-urlencoded
Content-Length: 319

{
 "query": {
  "type": "completions",
  "file": "#0",
  "end": {
   "line": 3,
   "ch": 2
  },
  "docs": true,
  "urls": true,
  "includeKeywords": true,
  "types": true
 },
 "files": [{
   "type": "full",
   "name": "main.js",
   "text": "var m = require(\"./module.js\");\r\nm.fooBar();\r\nm.baz();\r\nm.\r\n"
  }]
}
```

And tern replied with:

```
{
    "start": 58,
    "end": 58,
    "isProperty": true,
    "isObjectKey": false,
    "completions": [
        {
            "name": "baz",
            "type": "fn()"
        },
        {
            "name": "bazK",
            "type": "fn()"
        },
        {
            "name": "bazKi",
            "type": "fn()"
        },
        {
            "name": "bazKir",
            "type": "fn()"
        },
        {
            "name": "bazKirk",
            "type": "fn()"
        },
        {
            "name": "fooBar",
            "type": "fn()"
        }
    ]
}
```
As you can see the wrong completions are coming from tern. If I restart the server after the user "Save" file command - completion are parsed properly, I wanted to avoid this by using the `reset` command

**Comment by marijnh** [comment]
Ah, what you're doing here is not the right approach. And I've realized that my reset implementation is also problematic (it won't, for example, reload files listed as `loadEagerly` in your project settings). So I've reverted it again.

You should not be resetting the server every time a file changes, but instead you should upload a new version of the file with your next request (or push it to the server when, for example, moving away from a buffer).

**Comment by eranif** [comment]
> You should not be resetting the server every time a file changes, but instead you should upload a 
> new version of the file with your next request (or push it to the server when, for example, moving 
> away from a buffer).

Will this force a re-parse of files "included" implicitly? (in my above example: `module.js` is parsed implicitly)

**Comment by eranif** [comment]
> or push it to the server when, for example, moving away from a buffer

How do I do this? I can't find the proper API for this in the docs

**Comment by marijnh** [comment]
You can create a request with just a `files` field and no `query` field to push new files. Files included in requests are always re-parsed before the request is run.

**Comment by eranif** [comment]
Unfortunately, this does not work. I am still getting the messy code completion (as seen in the screenshot above)

Once a file is saved, I am sending a request to `tern` similar to:

```
{
 "files": [{
   "type": "full",
   "name": "modules\\inner.js",
   "text": "..file content goes here..."
  }]
}
```

It does not seem to have any effect. Any ideas?

**Comment by marijnh** [comment]
How are you updating the server's representation of `module.js`?

**Comment by eranif** [comment]
By sending this command:

```
{
 "files": [{
   "type": "full",
   "name": "module.js",
   "text": "..file content goes here..."
  }]
}
```

**Comment by marijnh** [comment]
That looks sane. When sending a new version of a file (as per the `name` field), properties defined by the old version should be erased. And in fact, this works for other Tern plugins (at least, I can't reproduce this issue in Emacs or the online demo), but somehow it's not working for you.

**Comment by eranif** [comment]
It usually works fine without the need to restart `tern` unless the active buffer is including another `js` file via the require function and __that__ file was modified.

I did also check that the `name` property is the same as `tern` sees it via the `files` command.

**Comment by marijnh** [comment]
I'm out of ideas. Maybe log requests (using `tern --verbose`) from another editor plugin, recreate the same situation, and see how those requests differ from the one your code is generating.

**Comment by eranif** [comment]
Can you recommend such a plugin to try with `tern --verbose` ?

**Comment by marijnh** [comment]
The [Sublime Text](https://github.com/marijnh/tern_for_sublime) and [Emacs](http://ternjs.net/doc/manual.html#emacs) plugins will connect to an existing server if you start it in the project directory before opening the file.
