### ISSUE TITLE
TypeError: Cannot read property 'charCodeAt' of undefined at isInteger 

### ISSUE THREAD

**Issue by tststs** [marijnh/tern#654]
### Example:

![bildschirmfoto 2015-09-30 um 13 51 41](https://cloud.githubusercontent.com/assets/3591665/10192192/d4464702-677a-11e5-8a95-cfb76bc4fb79.png)

Happens if i request type at the cursors position as seen in the screenshot.
I can't really tell when the error starts to appear (standalone this file works flawless). Classes e.g normally work perfectly. Hope this is enough information.

### .tern-project:
```
{
  "libs": [
    "browser",
    "ecma5",
    "ecma6"
  ],
  "loadEagerly": [
    "app/js/**/*.js"
  ],
  "plugins": {
    "complete_strings": {},
    "es_modules": {},
    "doc_comment": {
      "fullDocs": true
    }
  }
}
```

### Output:

/Users/tobiasschubert/github/atom-ternjs/node_modules/tern/lib/infer.js:535 var c0 = str.charCodeAt(0) ^ TypeError: Cannot read property 'charCodeAt' of undefined at isInteger (/Users/tobiasschubert/github/atom-ternjs/node_modules/tern/lib/infer.js:535:17) at extend.hasProp (/Users/tobiasschubert/github/atom-ternjs/node_modules/tern/lib/infer.js:569:11) at extend.getProp (/Users/tobiasschubert/github/atom-ternjs/node_modules/tern/lib/infer.js:601:24) at walk.simple.VariableDeclaration (/Users/tobiasschubert/github/atom-ternjs/node_modules/tern/plugin/doc_comment.js:64:35) at c (/Users/tobiasschubert/github/atom-ternjs/node_modules/tern/node_modules/acorn/dist/walk.js:39:16) at Object.exports.searchVisitor.walk.make.Statement (/Users/tobiasschubert/github/atom-ternjs/node_modules/tern/lib/infer.js:1929:7) at c (/Users/tobiasschubert/github/atom-ternjs/node_modules/tern/node_modules/acorn/dist/walk.js:38:15) at Object.base.Program.base.BlockStatement (/Users/tobiasschubert/github/atom-ternjs/node_modules/tern/node_modules/acorn/dist/walk.js:179:5) at c (/Users/tobiasschubert/github/atom-ternjs/node_modules/tern/node_modules/acorn/dist/walk.js:38:15) at Object.exports.searchVisitor.walk.make.Statement (/Users/tobiasschubert/github/atom-ternjs/node_modules/tern/lib/infer.js:1929:7)

Thanks and greetings,
tststs

**Comment by marijnh** [comment]
This should be fixed in the current master branch and release 0.15 (see #624). Try upgrading.

**Comment by tststs** [comment]
I'm running 0.15.1 at the moment. I'll try to downgrade and see if the error still occurs.

**Comment by marijnh** [comment]
On closer look, this is the same stack trace tail as the other bug, but a different origin. Attached patch should help.

**Comment by tststs** [comment]
Works like a charm!
Thanks
