### ISSUE TITLE
[ES6] First char completion in arrow functions is buggy

### ISSUE THREAD

**Issue by piotrtomiak** [marijnh/tern#659]
In the following example:
```javascript
var numbers = [1,2,3,4,5];
numbers.map(a => );
```
If I place cursor directly after => completion proposals show "a", but if I move cursor to the right by one, so that there is a space, "a" is not listed.

**Comment by marijnh** [comment]
What was happening is that the parser considers that cursor position to no longer be part of the arrow function node, so Tern ends up getting completions from the scope outside of the arrow function.

Acorn patch https://github.com/marijnh/acorn/commit/ec539d338d7318bd668185b65689f27a553fac3f should fix this.

**Comment by piotrtomiak** [comment]
Thanks!
